### ISSUE TITLE
Fix Mehtab Hassan typo

### ISSUE THREAD

**Issue by Me0wCat** [mahtab2003/Xera#1]
Please replace Mehtab Hassan with Mahtab Hassan.
![image](https://user-images.githubusercontent.com/103356908/168571434-f8e409e8-efd7-4566-9f12-83736ed75e2b.png)

**Comment by mahtab2003** [comment]
Thats not a typo my true name is Mehtab Hassan but i like to write it as Mahtab Hassan

**Comment by Me0wCat** [comment]
> Thats not a typo my true name is Mehtab Hassan but i like to write it as Mahtab Hassan

Ok.
