### ISSUE TITLE
Github Oauth is not working

### ISSUE THREAD

**Issue by webersec** [mahtab2003/Xera#100]
Github OAuth redirects to a blank page.

**Comment by mahtab2003** [comment]
Will be reviewed.

**Comment by santydesignscr** [comment]
We found the solution, please wait until @mahtab2003 modify the affected file because I can't do a pull request because my fork is currently broken due changes made that I'm currently working on it

**Comment by santydesignscr** [comment]
Hello, it is fixed now, please get the latest development version

**Comment by brosec** [comment]
Tried the latest version but got the same error

**Comment by santydesignscr** [comment]
@brosec You need to use the development version

**Comment by RaannaKasturi** [comment]
> Tried the latest version but got the same error

You might've added the wrong credentials. It's working perfect with the latest version. Just checked it

**Comment by webersec** [comment]
@RaannaKasturi i have filled the right creds but still it shows up blank page https://example.com/c/github_oauth?code=xxxxxxxxxxxxxxxxxxx

**Comment by webersec** [comment]
is it because i haven't enabled the device flow?

**Comment by webersec** [comment]
@santydesignscr could you please guide?

**Comment by santydesignscr** [comment]
Ok so let's debug

**Comment by santydesignscr** [comment]
Because it is working for me

**Comment by santydesignscr** [comment]
Did you make it work?

**Comment by webersec** [comment]
no, when a user authorise it using github then it shows up the callback url with a token and whenever tried manually refreshing the page it redirects back to the login page with a error msg "Invalid client or secret key."

**Comment by santydesignscr** [comment]
Did you created an app or oauth app?

**Comment by santydesignscr** [comment]
Are you using the latest development version?

**Comment by webersec** [comment]
yeah i am using the lastest development version.

**Comment by webersec** [comment]
yes i have already created one under developers/oauth apps.

**Comment by santydesignscr** [comment]
Ok, can we speak by private to access your website and debug the problem?

**Comment by webersec** [comment]
yeah sure!

**Comment by santydesignscr** [comment]
Ok this is my telegram: https://t.me/soy_santiago

**Comment by santydesignscr** [comment]
The problem was because user's browser cache so Xera was not the problem
