### ISSUE TITLE
cannot register admin account

### ISSUE THREAD

**Issue by EZnetworkAbsolutely** [mahtab2003/Xera#102]
After the configuration where i put the database details the website redirected me to the page to register the admin account, but it gives me error 404. i'm using a subdomain but i don't think that is the problem, if yes, how can i create a new directory on my principal domain

**Comment by EZnetworkAbsolutely** [comment]
i think the problem is the .htacces file 
1. i can't find it
2. and there's something wrong with it because every time i go in another page i always have to put "index.php" in the url

**Comment by mahtab2003** [comment]
The problem can be either in .htaccess file or in app/config/config.php
