### ISSUE TITLE
Cant connect Ip

### ISSUE THREAD

**Issue by JunayedRafi** [mahtab2003/Xera#103]
ERROR :The API ip address calling (185.27.134.81) does not match the allowed ip address. Please log into your reseller panel and ensure that your server ip address is listed in the 'allowed ip address' option of the api section1 . 185.27.134.81 . The API ip addresscalling (185.27.134.81) does not match the allowed ip address. Please log into your reseller panel and ensure that your server ip address is listed in the 'allowed ip address' option of the api section2. 185.27.134.81 .

**Comment by mahtab2003** [comment]
You should put ip 185.27.134.81 in your reseller panel > whm settings.
