### ISSUE TITLE
Problem with multiple user replies in ticket section

### ISSUE THREAD

**Issue by tanguy-fgl** [mahtab2003/Xera#104]
Hi Mahtab,
There is a problem with ticket replies. When a user add to replies, there is a unknow error. I think it replies to himself but I'm not sure. And there is no error when the user replies to the admin/support user.

When you have a normal discussion, there is no error:
![image](https://github.com/mahtab2003/Xera/assets/44116544/778bca32-ace4-40db-a635-320c17693919)
But when you add a reply to your reply, there is a unknow error
![image](https://github.com/mahtab2003/Xera/assets/44116544/797e2023-a7c2-4545-8d86-46f6dc853e66)

**Comment by tanguy-fgl** [comment]
And also, when you have such as enormous conversation. The page makes time to load, like 10 to 30s to load

**Comment by mahtab2003** [comment]
> And also, when you have such as enormous conversation. The page makes time to load, like 10 to 30s to load

For the first one, I will let you know once i dig that problem up.
For second one, this problem can be solved by adding pagination feature to the ticket page.

**Comment by tanguy-fgl** [comment]
> > And also, when you have such as enormous conversation. The page makes time to load, like 10 to 30s to load
> 
> For the first one, I will let you know once i dig that problem up. For second one, this problem can be solved by adding pagination feature to the ticket page.

It is on the view ticket page also

**Comment by mahtab2003** [comment]
> > > And also, when you have such as enormous conversation. The page makes time to load, like 10 to 30s to load
> > 
> > 
> > For the first one, I will let you know once i dig that problem up. For second one, this problem can be solved by adding pagination feature to the ticket page.
> 
> It is on the view ticket page also

Well i know bro, i will fix it as soon as i have some free time to spare.

**Comment by santydesignscr** [comment]
I will fix this, but first I will fix an issue with SMTP, when I finish I will create a pull request

**Comment by santydesignscr** [comment]
Ready, I fixed the self-reply bug, now I will add the pagination to tickets (if I can't today I will to it tomorrow). If you want to use my fixed version get Xera from my repo: https://github.com/santydesignscr/Xera or wait until my pull request is merged.

@mahtab2003 please see my pull request

**Comment by santydesignscr** [comment]
All fixed and pagination added, maybe close?
