### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tanguy-fgl** [mahtab2003/Xera#11]
I'm working to translate Xera in other languages with an automated detection of the default browser, my system is working great in other projects and I want to integrate it on all pages. Is there a file that Xera load on all pages? I just have to integrate this code on all the pages and it will be finished:
`<?php
$lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
$acceptLang = ['fr', 'en'];
$lang = in_array($lang, $acceptLang) ? $lang : 'en';
require_once "app/language/{$lang}.php"; /*I just have to create the languages files using php arrays*/
?>`

**Comment by mahtab2003** [comment]
no need to use that just follow this http://codeigniter.com/userguide3/libraries/language.html

**Comment by tanguy-fgl** [comment]
Thanks it worked
![image](https://user-images.githubusercontent.com/44116544/178457165-89afc3d4-879b-408f-b7c3-31f8afc972c7.png)
I just want to adapt the <option> to the theme if it's light or dark, other <option> are adapting to the theme but not my language selection so is there a class for that?

**Comment by tanguy-fgl** [comment]
Like this one
![image](https://user-images.githubusercontent.com/44116544/178457577-b8ad79cd-f0a2-40ca-996e-96b458bf7430.png)

**Comment by mahtab2003** [comment]
Maybe no

**Comment by tanguy-fgl** [comment]
Ok, to change the theme you use a form but where does it sends the value because I want to add a toggle switch button for the theme (I think it's better) but I didn't find how to post it

**Comment by mahtab2003** [comment]
Xera uses cookies to change theme.
