### ISSUE TITLE
ACME SSL not working

### ISSUE THREAD

**Issue by GGLVXD** [mahtab2003/Xera#115]
The ACME SSL is not working because i did set up all 3 of them and they should be correct enough but when i try to add an ssl it loads forever for like 2 - 3 min then it ig gets an response that it is added but when i go to the ssl list it again keeps loading until i get error 500 and it did not add any ssl certificate to website

**Comment by santydesignscr** [comment]
Please share your current configuration on acme SSL, censure kid and hmca because that are sensitive info

**Comment by GGLVXD** [comment]
![Screenshot_20240710-184802_Chrome~2](https://github.com/mahtab2003/Xera/assets/85647114/fd368a57-8c9e-41a9-82c9-c004dfb156a5)

**Comment by santydesignscr** [comment]
Are you using Xera in a MOFH account, right?
I'm now testing all before the new release, your config seems to be ok, I will debug the orror on a MOFH test website and let you know when it is fixed

**Comment by GGLVXD** [comment]
Yeah its running on mofh account

**Comment by santydesignscr** [comment]
In fact there's an error, i fixed it now, soon I will update the code to fix, but as I see ACME SSL is too slow on MOFH

**Comment by santydesignscr** [comment]
It's working perfect on another hosting

**Comment by GGLVXD** [comment]
Oh

**Comment by santydesignscr** [comment]
I will try to improve the performance on MOFH, but there's not much to do

**Comment by santydesignscr** [comment]
Are you free now to show you how's it going?

**Comment by GGLVXD** [comment]
Yeah

**Comment by santydesignscr** [comment]
This is my byet forums porfile:
https://www.byet.net/index.php?/profile/600675-santiago/
Send me a PM

**Comment by betasio** [comment]
bro once updated add a new release the release is the same from 3 weeks update the version as well thanks.

**Comment by santydesignscr** [comment]
Hello, that's development version, that's why I don't update the version, when I release the new version I will change it

**Comment by santydesignscr** [comment]
Xera developement version was updated and the issue fixed, next release soon

**Comment by webersec** [comment]
![reqssl](https://github.com/user-attachments/assets/a0671b26-3e0b-4178-b85f-4a2ab0af095e)

**Comment by webersec** [comment]
@santydesignscr whenever clients try to create ssl it shows like the above screenshot.

**Comment by santydesignscr** [comment]
Can you share your current ACME and GoGetSSL configurations?, censure sensitive info

**Comment by brosec** [comment]
@santydesignscr can you explain the steps to generate Google Trust EAB Key id?

**Comment by GGLVXD** [comment]
> @santydesignscr can you explain the steps to generate Google Trust EAB Key id?

https://cloud.google.com/certificate-manager/docs/public-ca-tutorial
Everything is here

**Comment by santydesignscr** [comment]
For all setup things please refer to: https://github.com/mahtab2003/Xera/blob/dev/Setup-Guide.md

**Comment by santydesignscr** [comment]
@GGLVXD @brosec, do you had any problems with Xera?

**Comment by brosec** [comment]
Isn't it possible to use simply gogetssl , zerossl and letsencrypt without using google trust and cloudflare?

**Comment by santydesignscr** [comment]
> ![reqssl](https://private-user-images.githubusercontent.com/83569731/348271374-a0671b26-3e0b-4178-b85f-4a2ab0af095e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTYzNjIsIm5iZiI6MTcyMDgxNjA2MiwicGF0aCI6Ii84MzU2OTczMS8zNDgyNzEzNzQtYTA2NzFiMjYtM2UwYi00MTc4LWI4NWYtNGEyYWIwYWYwOTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIwMjc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYzgwYzNiMjE3NjM2MDc0ZmM2NDhmZjI3YjJiZjE3MzFhMzE3NmU5N2VjMDVhNzBhYTQxYzY5ZjFiMzQxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hug0Sfgh5hoklJ0AY-Y8dmyyZ9xYjExKQei55_Tz7Hw)

Like this

**Comment by santydesignscr** [comment]
> Isn't it possible to use simply gogetssl , zerossl and letsencrypt without using google trust and cloudflare?

Yes you can uses the ones that you want but cloudflare is mandatory for CNAME delegation

**Comment by santydesignscr** [comment]
Just leave the inputs empty

**Comment by brosec** [comment]
Yeah i've also got the same error i think its because i have only added gogetssl, letsencrypt directory url, zero ssl url and the keys

**Comment by santydesignscr** [comment]
Yeah, you forgot cloudflare, I will make that required

**Comment by santydesignscr** [comment]
I will add on the docs that clouflare is mandatory

**Comment by brosec** [comment]
So if i add the cloudflare config then it will work without adding the google trust config

**Comment by brosec** [comment]
![IMG_20240713_021238](https://github.com/user-attachments/assets/72bf7967-699c-44a6-96c7-4cc4ac21157a)

Should i leave this as it is?

**Comment by santydesignscr** [comment]
Yes

**Comment by santydesignscr** [comment]
If you are on a paid hosting you can disable DNS over HTTPS and use any dns resolver that you like

**Comment by brosec** [comment]
@santydesignscr its working you can close the issue.

**Comment by santydesignscr** [comment]
Ok, thanks for your confirmation
