### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by GGLVXD** [mahtab2003/Xera#129]
SMTP doesnt seem to work anymore. My config seems fine.

**Comment by RaannaKasturi** [comment]
Yes. SMTP fails no matter which server do we use.. I was working perfectly until tge latest release. After that, it started to having issues

**Comment by betasio** [comment]
well yeah smtp doesn't work but what i did to fix that was revert the smtp function to 1.2.8 and use the fix which was for it then i finally managed to fix it

**Comment by RaannaKasturi** [comment]
> well yeah smtp doesn't work but what i did to fix that was revert the smtp function to 1.2.8 and use the fix which was for it then i finally managed to fix it

I'm not good with PHP, I'm a python developer shifting to JS. So, can you explain, what actually needs to be reverted back..?

**Comment by GGLVXD** [comment]
> > well yeah smtp doesn't work but what i did to fix that was revert the smtp function to 1.2.8 and use the fix which was for it then i finally managed to fix it
> 
> I'm not good with PHP, I'm a python developer shifting to JS. So, can you explain, what actually needs to be reverted back..?


Revert this [commit](https://github.com/mahtab2003/Xera/commit/6e2d4f64497d3898ccc2e5d0e7f3e437b6ee0f58)

**Comment by betasio** [comment]
well what i did was go to app/models/mailer.php replace the whole code with the code of xera version 1.2.8

and go to app/config/email.php and add 

$config['smtp_crypto'] = 'tls';

then  go to system/libraries/email.php

in line 180 replace 

public $newline		= "\n";

with

public $newline		= "\r\n";

and thats how i managed to fix the issue i got it working

**Comment by santydesignscr** [comment]
Hello, sorry for being inactive, currently Xera is under a complete core review and migration to Codeigniter 4 so there will not be updates for now, about SMTP change the new line character to \r\n, TLS crypto is set automatically based on API settings

**Comment by RaannaKasturi** [comment]
Thankyou so much. It worked
