### ISSUE TITLE
Account stuck on "PENDING"

### ISSUE THREAD

**Issue by bopv2** [mahtab2003/Xera#13]
When I try to make a new account its stuck on PENDING

In account panel:
![image](https://user-images.githubusercontent.com/97548973/179352142-ec8faa33-92da-4d76-a5d5-5799f5d6bf73.png)

In admin panel:
![image](https://user-images.githubusercontent.com/97548973/179352109-6d92d7f0-8810-4999-970c-f230905efccc.png)
![image](https://user-images.githubusercontent.com/97548973/179352185-4dbfc1e8-916c-41a6-9c8b-73ecc7dce2c9.png)

In MOFH Panel:
![image](https://user-images.githubusercontent.com/97548973/179352123-0cc708ca-fb96-4f4f-97eb-8e6bfc8a44e2.png)

Website:
https://control.cpvp.ga

Version:
Latest (today I updated and used my backed up config)

**Comment by bopv2** [comment]
@mahtab2003 please man

**Comment by mahtab2003** [comment]
> @mahtab2003 please man

Dear fellow use this http://control.cpvp.ga/c/mofh as mofh callback

**Comment by bopv2** [comment]
Thanks! I missed out on that part lol

**Comment by mahtab2003** [comment]
You are welcome
