### ISSUE TITLE
acme ssl not working

### ISSUE THREAD

**Issue by GGLVXD** [mahtab2003/Xera#131]
LetsEncrypt and GoogleTrust doesnt work. Lets encrypt is stuck on pending when requesting and Google trust is stuck on Ready. Zerossl gonna work when ever it gonna want to (it worked once now again for some reason it didnt work, i dont know why is this hapenning and you cant really disable letsencrypt i removed the directory url for it but it replaces with not-set and still shows up on the list.

**Comment by santydesignscr** [comment]
Google Trust will not work due some Google policies, for now it will not be fixed I'm focused on migrating Xera to Codeigniter 4

**Comment by santydesignscr** [comment]
It's not stuck, DNS on MOFH is very slow to propagate so you need to wait, InfinityFree is faster because they use their own dns to set the DNS challenge. Xera will not put ready status until dns is propagated on the set dns resolver, if you're hosting Xera on free hosting don't change it

**Comment by santydesignscr** [comment]
Changed DNS delegation method (cloudflare removed), this will improve Let's Encrypt, Google Trust not suported

Will be aplied no next release (today)
