### ISSUE TITLE
SSL Problem !

### ISSUE THREAD

**Issue by itsmerosu** [mahtab2003/Xera#132]
After using the latest version of XERA for a while, I encountered an SSL error while testing an upgrade. Please fix this issue in the next update. In the meantime, please give me some steps to resolve this issue, since I have already set up all the details and would prefer not to delete everything and start over.
@4yx @FuryCraft @mahtab2003 @santydesignscr 

![ss](https://github.com/user-attachments/assets/de64b277-7093-4d80-9937-977860b80d1a)

**Comment by itsmerosu** [comment]
Resolved !

**Comment by santydesignscr** [comment]
I will share with you a patch

**Comment by itsmerosu** [comment]
Thank you for the quick reply, but I changed some codes in create_ssl.php, and it's working now. Thank you.
