### ISSUE TITLE
Ticket Reply Problem !

### ISSUE THREAD

**Issue by itsmerosu** [mahtab2003/Xera#133]
I am using the latest XERA and everything working fine but I figured out one problem on my system. When I respond to any ticket, the ticket reply post mail goes to 1st account email on the database (is_user), but not to the account email that created the ticket.

In summary,
Ticket Created Account Email: [100@gmail.com](mailto:100@gmail.com)
Ticket Responed Email Send to: [1@gmail.com](mailto:1@gmail.com) (This email is my 1st used email as a client in my xera dashboard)

Any solution for this @mahtab2003 @4yx @FuryCraft @santydesignscr 

![Screenshot_15-7-2024_221824_mail google com](https://github.com/user-attachments/assets/6b79714a-72b7-4ba3-8e59-d61a6a715c07)

A ticket ticket-created email was sent to the admin email and a Ticket Reply was also sent in 1 email on the database. you can check the screenshot for proof.

Replied Screenshot:
![Screenshot_15-7-2024_222653_app dep com np](https://github.com/user-attachments/assets/7c525ccf-124c-4f4b-9a37-c2eeffcc47ab)

Received an Email on roxxxxxx98@gmail.com but the ticket open email is cacxxxxx@stxxxxxz.com so reply mail need to be send to cacxxxxx@stxxxxxz.com not in roxxxxxx98@gmail.com. and remember roxxxxxx98@gmail.com is my 1 created user in my database or 1st user on is_user table. please cross check my email , name etc
![Screenshot_15-7-2024_222824_mail google com](https://github.com/user-attachments/assets/51bd4765-f376-4330-9be7-03cef9506c5f)

Delivery Email Report: **READ CAREFULLY** 
![Screenshot_15-7-2024_231832_s1321 sgp1 mysecurecloudhost com](https://github.com/user-attachments/assets/ff1dd2d3-bdc2-42ca-8e7b-951471529d3b)

Thank You

**Comment by santydesignscr** [comment]
Please keep only one issue open

**Comment by itsmerosu** [comment]
I am opening this issue because of the latest data and screenshots for better understanding. Please proceed with your upgrade, but provide a guide to address this issue, as I will manage it myself. Thank you for your time.

**Comment by santydesignscr** [comment]
Ok, I will open, it's not easy to address that error, I tried but not found now, I wasn't able to replicate, but it will be fixed in the next release

**Comment by santydesignscr** [comment]
I will try to do it as soon as it is posible

**Comment by itsmerosu** [comment]
Please resolve this issue and release a new update as soon as possible.

**Comment by santydesignscr** [comment]
Yes I will try to do it soon, but remember, everyone has a life (or it should be) and I'm not getting anything for working on Xera, so please be comprensive

**Comment by mahtab2003** [comment]
> everyone has a life (or it should be) and I'm not getting anything for working on Xera, so please be comprensive

The only reason i left xera

**Comment by itsmerosu** [comment]
> The only reason i left xera

😥😥

**Comment by santydesignscr** [comment]
I will not leave Xera like him, I will try to maintain slowly but will do my best.

**Comment by itsmerosu** [comment]
> I will not leave Xera like him, I will try to maintain slowly but will do my best.

Sounds great! Thank you.

**Comment by itsmerosu** [comment]
FIXED
