### ISSUE TITLE
Need Help create_account.php

### ISSUE THREAD

**Issue by itsmerosu** [mahtab2003/Xera#135]
Hello @santydesignscr 

I need a little help with create_account.php. I want to make the Account Label field optional. I tried setting the <input to disabled="true", but it didn't work.

Please provide a small piece of code that I can implement in my live production.

![ss (2)](https://github.com/user-attachments/assets/629fa969-fabd-4749-adde-390d380e5bc7)

I really appreciate any help you can provide.

**Comment by santydesignscr** [comment]
Set value="Default Account Label" inside input tag, but all accounts will have the same label

**Comment by itsmerosu** [comment]
Thanks, but I have another issue. When a user creates a new hosting account, the account details email is sent twice.

Mails:
![Screenshot_17-7-2024_225422_s1321 sgp1 mysecurecloudhost com](https://github.com/user-attachments/assets/66da8f94-41b9-4194-a9d2-4a4880987975)

Same details but mail twice. 

Any idea

**Comment by santydesignscr** [comment]
You're having weird problems with email that no one reported, and I haven't hable to replicated, is your SMTP server ok?

**Comment by itsmerosu** [comment]
I have used XERA on other servers, but I encountered the same problem. My STMP server is working fine. I faced the same error on my old server, so I opened issue #89, but I didn't get any response, so I discontinued using XERA. Now that new updates are being released, I tried again, but the same issue is showing up. Please remember that this is a new server.

**Comment by santydesignscr** [comment]
I see, now we are working on a new release of Xera, it will be improved and fix all of this errors

**Comment by itsmerosu** [comment]
Okey sir thank you

**Comment by mahtab2003** [comment]
Error related to this issue had been fixed in new update and will release soon
