### ISSUE TITLE
Account Pending Error !

### ISSUE THREAD

**Issue by itsmerosu** [mahtab2003/Xera#137]
Hello @santydesignscr 

I am encountering a strange pending error on XERA. After attempting SSL, I tried to manage it, and now a pending error is displayed. Some users not getting those errors but some of them are facing the same errors.

![gif](https://github.com/user-attachments/assets/cf8166cd-5990-4847-a21c-a90656de7c23)

Thank you

**Comment by santydesignscr** [comment]
Will be fixed on the next release

**Comment by itsmerosu** [comment]
Thanks
