### ISSUE TITLE
Custom domain for ACME challenge

### ISSUE THREAD

**Issue by LightHostingFree** [mahtab2003/Xera#144]
If I want custom domain ACME challenges, How can I setup it

**Comment by itsmerosu** [comment]
> If I want custom domain, How can I setup it

Can you please clear your "CUSTOM DOMAIN" issue?

**Comment by santydesignscr** [comment]
> If I want custom domain, How can I setup it

You can't

**Comment by LightHostingFree** [comment]
> > If I want custom domain, How can I setup it
> 
> You can't

I know we can't, but we want to

**Comment by LightHostingFree** [comment]
> If I want custom domain for ACME challenges, How can I setup it

**Comment by santydesignscr** [comment]
Ok, you need a VPS to run [ACME-DNS](https://github.com/joohoi/acme-dns) software, after that you need to update DNS API endpoint in app/models/Acme.php on each block of code where ACME-DNS API is called:

Replace all of the occurrences of:
`$acmednsUrl = 'https://auth.acme-dns.io';`
With:
`$acmednsUrl = 'your own acme dns api endpoint';`

**Comment by LightHostingFree** [comment]
> Ok, you need a VPS to run [ACME-DNS](https://github.com/joohoi/acme-dns) software, after that you need to update DNS API endpoint in app/models/Acme.php on each block of code where ACME-DNS API is called:
> 
> Replace all of the occurrences of: `$acmednsUrl = 'https://auth.acme-dns.io';` With: `$acmednsUrl = 'your own acme dns api endpoint';`

Can't we get cloudflare dns back? It is relatively more secure.

**Comment by santydesignscr** [comment]
Yes you can restore the code from the old version but CloudFlare is not recommended due their 1000 dns records limit and some issues with Let's Encrypt
