### ISSUE TITLE
Lastest release user email verification show  "Invalid activation token".

### ISSUE THREAD

**Issue by ash3T** [mahtab2003/Xera#157]
hi, Thanks for your continue hard work.

I just installed the latest version 1.3.1. 

Tried to register serveral new users, after clicked the linked send to user's email, it says, "Invalid activation token." Please take a look.

**Comment by itsmerosu** [comment]
Some users are encountering an error on their server. Please check the app/models/mailer.php and change the newline character to `<br>` This should fix your problem.

**Comment by santydesignscr** [comment]
> hi, Thanks for your continue hard work.
> 
> I just installed the latest version 1.3.1.
> 
> Tried to register serveral new users, after clicked the linked send to user's email, it says, "Invalid activation token." Please take a look.

A blank space is added due some email configuration, I will share a fix soon

**Comment by santydesignscr** [comment]
> Some users are encountering an error on their server. Please check the app/models/mailer.php and change the newline character to `<br>` This should fix your problem.

Try that but if it doesn't work don't worry I will share a solution soon

**Comment by kaitokun24** [comment]
Just change the newline on /app/models/mailer.php

from `'newline' => "\r\n" `to `'newline' => '\r\n'`

![Screenshot 2024-09-03 at 7 50 46 AM](https://github.com/user-attachments/assets/730c2d3f-84c2-4835-a6ab-4f94f17dda56)

**Comment by santydesignscr** [comment]
> Just change the newline on /app/models/mailer.php
> 
> from `'newline' => "\r\n" `to `'newline' => '\r\n'`
> 
> ![Screenshot 2024-09-03 at 7 50 46 AM](https://private-user-images.githubusercontent.com/75037631/363805910-730c2d3f-84c2-4835-a6ab-4f94f17dda56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTE4ODcsIm5iZiI6MTcyNTkxMTU4NywicGF0aCI6Ii83NTAzNzYzMS8zNjM4MDU5MTAtNzMwYzJkM2YtODRjMi00ODM1LWE2YWItNGY5NGYxN2RkYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE5NTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NDg3MWViZmUwMjdkNmM3OGMxZjYwYjNhNWY4MDZhNDFmZjI5NDM3ZmUzOWUzNTdlODgyMWU0N2IwOWMxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U4u3RqWgVCtSTqLL0ylPUlhI1qqSa5_CJu51C-9LOLA)

Yeah that's the solution, will be properly fixed on the next release
