### ISSUE TITLE
Discord 0auth

### ISSUE THREAD

**Issue by ghost** [mahtab2003/Xera#158]
I would like to be able to use discord 0auth for my clients it would also be nice if the auto updater worked.

**Comment by itsmerosu** [comment]
Currently, @santydesignscr is not planning to migrate to Codeigniter 4 immediately but will continue working on it.

**Comment by santydesignscr** [comment]
As @itsmerosu said I'm not planning to add more features, I'm focused in migrating Xera to Codeigniter 4 first.
