### ISSUE TITLE
SSL Cert not working

### ISSUE THREAD

**Issue by TheAutisticChicken** [mahtab2003/Xera#159]
I added an SSL certificate to my site, provided by ZeroSSL and the client or admin page(s) won't load.

Is this an xera thing or a cPanel error?

**Comment by mahtab2003** [comment]
What error are you facing like what is the error which is displayed on the screen?

**Comment by TheAutisticChicken** [comment]
There isn’t one on the screen.

Just no CSS loads and you can’t submit it any login forms

Link: https://client.vortexdigital.co.uk

**Comment by mahtab2003** [comment]
in the app/config/config.php replace http:// with https:// in base_url value and it will be solved.

**Comment by TheAutisticChicken** [comment]
Thank you!
