### ISSUE TITLE
Add Site.pro

### ISSUE THREAD

**Issue by vietnga20081** [mahtab2003/Xera#161]
How do I add a site.pro site builder Can you give me a more detailed guide?

**Comment by itsmerosu** [comment]
Sitepro Integration: Refer to [Sitepro API Documentation](https://site.pro/API-documentation/create-session-sso/1141640/) 
Hostname: Set to https://site.pro.
Username: Enter your Sitepro username
Password: Enter your Sitepro password.
Status: Set to Active to enable the integration.

**Comment by vietnga20081** [comment]
![Screenshot 2024-08-31 093209](https://github.com/user-attachments/assets/6016ad47-d001-42f8-99b0-d7bcce834e0a)
![Screenshot 2024-08-31 093329](https://github.com/user-attachments/assets/33bb7f19-21a6-4e59-b84f-0a7443746d43)
![Screenshot 2024-08-31 093416](https://github.com/user-attachments/assets/9c453e91-0bf7-4e1c-a21b-f84133fbfcd1)
I accessed http://pld.id.vn/api/requestLogin and it reported error 404. Don't know where else to configure?

**Comment by itsmerosu** [comment]
Please make sure to check your API details as they appear to be incorrect. Kindly review and try again.
![Screenshot_31-8-2024_8297_site pro](https://github.com/user-attachments/assets/dc081994-c3da-4bc4-af9c-650a27c5bbed)

**Comment by vietnga20081** [comment]
Where can I get this api code? 
![Uploading Screenshot 2024-08-31 101002.png…]()

**Comment by itsmerosu** [comment]
@vietnga20081 You haven't read the documentation properly. Please read it carefully. or contact me on https://t.me/itsmeroosu

**Comment by vietnga20081** [comment]
I have contacted you via Telegram. Hope you help.

**Comment by santydesignscr** [comment]
Hello, if you have any issues again please open a new issue
