### ISSUE TITLE
http to https error

### ISSUE THREAD

**Issue by vietnga20081** [mahtab2003/Xera#162]
https://github.com/user-attachments/assets/f5852690-406a-4b2a-a848-803392ba7a4c

Error login for user. Admin login ok. Hiện tại tôi đang để https://pld.id.vn You check for me.

**Comment by mahtab2003** [comment]
working fine for me

**Comment by mahtab2003** [comment]
https://github.com/user-attachments/assets/2d52864a-48de-4e67-b025-61398487ec54


working fine for me

**Comment by vietnga20081** [comment]
Oke.
