### ISSUE TITLE
Error publish site.pro

### ISSUE THREAD

**Issue by vietnga20081** [mahtab2003/Xera#163]
[
![IMG_0552](https://github.com/user-attachments/assets/060a8c4e-a825-4f3c-acc9-0b63bf8ccab7)
Error publish site builder of site.pro

**Comment by santydesignscr** [comment]
Please contact me at cloudcode@santiago.webcr.top to debug the error.

**Comment by Keshavi15** [comment]
I am trying to add site.pro service but stuck at step 3 as in pic. I am on ifastnet premium hosting (shared). So, wondering can i be able to provide site.pro service via cPanel ? If yes, how can i proceed ahead? To install via SSH Access, need to be through root, i guess.
![site-pro-inq](https://github.com/user-attachments/assets/cf5b4c0f-7567-4da6-af23-71dc88dc0afb)

**Comment by greenreader9** [comment]
You don't install it, you link it via the API.

**Comment by Keshavi15** [comment]
Thank you very much for your reply, greenreader9. Being novice facing challenges to connect with site.pro API. Just to make sure. I could not find my site.pro API username and password. Do i have to use these details from link available at https://site.pro/API-documentation/create-session-sso/1143588/ . Looks like public username: apikey0 and password...
2. Do i have to create new subdomain to add site.pro API folder ?
3. Which way is the most recommended publication type ? external, internal, http, or local? 
4. If i pick internal publication type. How can i pick data such as 
'domain' => 'example.com',			// (required) domain of the user website you want to edit
Will $this->base->text('account_domains', 'heading') from xera used?
Site.pro API documentation didnt went through my head. If you can explain in details or provide me link to follow steps will be great help. Thanks in Advance.

**Comment by greenreader9** [comment]
1) Yes

2) No

3) External is the easiest. You can do internal but that would create a ton of work for yourself that is entirely unnecessary.

Hope this helps!

**Comment by ash3T** [comment]
Hi, I face the similar situation. I don't know how to link site.pro. 
<img width="865" alt="Screenshot 2024-11-19 at 9 06 42 PM" src="https://github.com/user-attachments/assets/182480e4-7880-479f-965f-5d7c2ba93d31">

I followed @greenreader9 's suggestion, filled in the following information in the admin panel. 

Username: apikey0
Password: Q.Avfuc/.hwrLZsQRwDSpWeOX/PIabBkzNEe2PPTrRkQOOT2

But it returns with error "Authorization required.", when click the sitebuilder button.

<img width="262" alt="Screenshot 2024-11-19 at 9 11 36 PM" src="https://github.com/user-attachments/assets/5032aca9-3fdb-480e-9bcc-3426133b84b1">

I don't know how to setup the external or internal, do I need to do anything else other than filled in the API username and password. 

Can anyone add more details in the setup guide. It might be easy and self-explanatory for some, but difficult for others. Any help will be highly appreciated.
