### ISSUE TITLE
Switching from HTTP to HTTPS

### ISSUE THREAD

**Issue by Keshavi15** [mahtab2003/Xera#166]
Hi there, I install Xera over http, tested well now moving to https, but base_url() is returning http so getting mixed content issue. Wondering how can i fix this simple trick. I am novice in this. if anyone can guide will be great. TIA

**Comment by mahtab2003** [comment]
edit app/config/config.php and update your site url

**Comment by Keshavi15** [comment]
Thanks Mehtab. Did and working. Thanks
