### ISSUE TITLE
MAIL VERIFICATION ERROR

### ISSUE THREAD

**Issue by davisvawiz** [mahtab2003/Xera#167]
When an account is opened and the verification email is sent, the link provided does not work.

**Comment by Keshavi15** [comment]
Hey jugleking-world I am new and testing xera too. May be issue with SPF setup. My first experience was email link was blocked by yahoo, cannot access. after setup it was sent to email, i tried google and yahoo both are working now. I guess If  your email test connection are working, link may work. If the link doesn’t work, you can copy and paste the following URL into your browser.

**Comment by itsmerosu** [comment]
Just change the newline on /app/models/mailer.php
from `'newline' => "\r\n" `to `'newline' => '\r\n'`

![Screenshot 2024-09-03 at 7 50 46 AM](https://github.com/user-attachments/assets/730c2d3f-84c2-4835-a6ab-4f94f17dda56)

**Comment by greenreader9** [comment]
> Just change the newline on /app/models/mailer.php
> 
> from `'newline' => "\r\n" `to `'newline' => '\r\n'`


If that is a working solution, create a PR to help others from experiencing this issue!

**Comment by davisvawiz** [comment]
Prefect thanks after changing from 'newline' => "\r\n" to 'newline' => '\r\n' it worked! Thanks @itsmerosu
