### ISSUE TITLE
SSL Delete Error

### ISSUE THREAD

**Issue by Keshavi15** [mahtab2003/Xera#169]
Hello Xera Family, I found two issues regarding pending SSL order removal. 
1. As a client, when i tried to delete SSL Order (pending), it displayed "An Error Occurred. Try Again later" 
2. As an Admin, when I tried to delete SSL Order (pending), it displays "An Error Occurred. Try Again later" and logs me out.

Any idea, how to fix this issue?

**Comment by itsmerosu** [comment]
> Hello Xera Family, I found two issues regarding pending SSL order removal.
> 
> 1. As a client, when i tried to delete SSL Order (pending), it displayed "An Error Occurred. Try Again later"
> 2. As an Admin, when I tried to delete SSL Order (pending), it displays "An Error Occurred. Try Again later" and logs me out.
> 
> Any idea, how to fix this issue?

Can you please mention your SSL provider too?

**Comment by Keshavi15** [comment]
hi itsmerosu, I tried with all SSL providers, as we get TXT records not CNAME records from lets Encrypt, ZeroSSL and Google. As a subdomain user I cannot pass acme_challange. So, status is pending and wanted to delete this SSL orders but unfortunately these are undeletable. 
![Screenshot 2024-10-15 055047](https://github.com/user-attachments/assets/be2be539-eac7-4a20-ac14-dec4647fe84d)

**Comment by itsmerosu** [comment]
> hi itsmerosu, I tried with all SSL providers, as we get TXT records not CNAME records from lets Encrypt, ZeroSSL and Google. As a subdomain user I cannot pass acme_challange. So, status is pending and wanted to delete this SSL orders but unfortunately these are undeletable. ![Screenshot 2024-10-15 055047](https://private-user-images.githubusercontent.com/176582587/376393583-be2be539-eac7-4a20-ac14-dec4647fe84d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTY2NjEsIm5iZiI6MTcyODk5NjM2MSwicGF0aCI6Ii8xNzY1ODI1ODcvMzc2MzkzNTgzLWJlMmJlNTM5LWVhYzctNGEyMC1hYzE0LWRlYzQ2NDdmZTg0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMjQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTA1Zjk2MzNlMjMyZDAwZmU1NjgyOTY4MTVkMjk5ZWQ2MTQ0MGY3NDg5ZGRhNTYyODRjMjg2Y2JhZTA1NmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3sstOF4cFuqeOI8Wmki_foxzURP3SDQVA2vSX3b_g0s)

Thank you for sharing your issue. We are unable to resolve the errors in this way as there are several possible causes. Please contact me at https://t.me/itsmeroosu
