### ISSUE TITLE
Hosting account Activation And Deactivation Issue

### ISSUE THREAD

**Issue by Keshavi15** [mahtab2003/Xera#170]
Hello Xera Family, 
I have an account activation and deactivation issue. 
1. When new hosting account is created, status remains **pending** forever. Never turns to **active**. To fix this issue temporarily, i have  changed 'account_status' => 'pending',  to 'account_status' => 'active' at line 183 in the file : app/models/mofh.php.  Looking for right solution.
2. When hosting account is requested for deactivation, status remains **deactivating**
![Screenshot 2024-10-04 223535](https://github.com/user-attachments/assets/9f3ce2f1-7f49-480f-be35-1db522cab98b)
, never deactivating. Seeking solution. 

Thanks In Advance!

**Comment by greenreader9** [comment]
To me, this means that you did not setup the callback in your MOFH account panel correctly

**Comment by Keshavi15** [comment]
Thanks **greenreader9**, http wasn't updated to https. Thanks very much.
