### ISSUE TITLE
Unable to verify domain availability

### ISSUE THREAD

**Issue by inakashsingh** [mahtab2003/Xera#172]
I have installed XERA but now after user sign in to their account  it stuck on the domain availability section nothing happens after clicking on the check availability button.

**Comment by inakashsingh** [comment]
Also I added my mofh api detail in xera but there is no response after clicking on the test connection button.

![Screenshot 2024-10-15 022447](https://github.com/user-attachments/assets/54f19530-b6ed-47f6-a765-a705ddda5aef)

**Comment by Keshavi15** [comment]
I guess, package name is not matching with your hosting plan name set at MOFH

**Comment by itsmerosu** [comment]
> I have installed XERA but now after user sign in to their account it stuck on the domain availability section nothing happens after clicking on the check availability button.



> Also I added my mofh api detail in xera but there is no response after clicking on the test connection button.
> 
> ![Screenshot 2024-10-15 022447](https://private-user-images.githubusercontent.com/72150622/376383394-54f19530-b6ed-47f6-a765-a705ddda5aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTY0MTUsIm5iZiI6MTcyODk5NjExNSwicGF0aCI6Ii83MjE1MDYyMi8zNzYzODMzOTQtNTRmMTk1MzAtYjZlZC00N2Y2LWE3NjUtYTcwNWRkZGE1YWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDEyNDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmQ4NTljOWM1ZGQ2MDkzMWM4YzQ4NDExMDdmM2VlMmMxODNmMDg3YjYxNzIwMWI4YjFkZmM3NGI2YzRmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WeevtmxCCWVHk9t-huCnNWEvPYXeHqW6eWe2lPh1bT8)

Please check your MOFH details. The panel cannot fetch those details from MOFH, so it is stuck.

**Comment by inakashsingh** [comment]
I checked all the details are correct and the package is also same

**Comment by Keshavi15** [comment]
Just wondering? Have you created free hosting plan in MOFH account where you set features like disk space. If you have created this plan and have named it, you can try using that name as Package in Xera API Setting. As you have put Package as **free** . Hopefully, this may be the issue. If you can pass **Test Connection**. Hopefully there wont be any issue.

**Comment by itsmerosu** [comment]
> I checked all the details are correct and the package is also same

Please create a new free hosting package and try again with new details. I hope this will help you; if not, don't hesitate to get in touch with me on Telegram [https://t.me/itsmeroosu](https://t.me/itsmeroosu)

**Comment by santydesignscr** [comment]
Please people, follow the Setup-Guide, and @itsmerosu thanks for replying the issues
