### ISSUE TITLE
After installation it does not register, some pages have 404 errors.

### ISSUE THREAD

**Issue by ORyong** [mahtab2003/Xera#176]
Register and redirect to mydomain/admin/regeister, but this page does not exist.
![Screenshot_20241031_102754_com microsoft emmx](https://github.com/user-attachments/assets/b7f26014-53c2-4a4c-8723-6d066da2a546)
![Screenshot_20241031_103113](https://github.com/user-attachments/assets/ca4eedb6-d73f-4414-8fcf-11fa3b4ed050)

**Comment by ORyong** [comment]
When I tried to install Xera, the last step of the installation step: redirection. Click the redirect button and you will jump to / admin / regeister. But the page is 404 and there is no directory in the host file directory.

**Comment by itsmerosu** [comment]
Please check your PHP configuration. Try changing the PHP version and reinstalling it.

**Comment by itsmerosu** [comment]
> When I tried to install Xera, the last step of the installation step: redirection. Click the redirect button and you will jump to / admin / regeister. But the page is 404 and there is no directory in the host file directory.



> Register and redirect to mydomain/admin/regeister, but this page does not exist. ![Screenshot_20241031_102754_com microsoft emmx](https://private-user-images.githubusercontent.com/169452446/381801980-b7f26014-53c2-4a4c-8723-6d066da2a546.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDE4NTAsIm5iZiI6MTczMDQ0MTU1MCwicGF0aCI6Ii8xNjk0NTI0NDYvMzgxODAxOTgwLWI3ZjI2MDE0LTUzYzItNGE0Yy04NzIzLTZkMDY2ZGEyYTU0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNjEyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTBjYzUwOGE2ZmM5MzYyNjJkMGI1YTY3Zjg3MjA5YzFmMTlkZTAzM2VkZDYzMjVkMTcxNDEwZTViMGJiYWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yRcABuV_YeSra6vYlWDEUlOQ8o_Uw85HO6cqSWpvu0w) ![Screenshot_20241031_103113](https://private-user-images.githubusercontent.com/169452446/381802289-ca4eedb6-d73f-4414-8fcf-11fa3b4ed050.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDE4NTAsIm5iZiI6MTczMDQ0MTU1MCwicGF0aCI6Ii8xNjk0NTI0NDYvMzgxODAyMjg5LWNhNGVlZGI2LWQ3M2YtNDQxNC04ZmNmLTExZmEzYjRlZDA1MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNjEyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTg0ZGRmMmUyYzI3NmFkNWE5YWYzZWFkNmY5MzNkMDE1OTU3ODE3MjIxZjdjMDFiNjE4MDBiYzg4NDIzMDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x12gjcS9c0RfwpamcEtNsO49KaWnTP8wn0ZMeRtsZ-Y)

Please check your PHP configuration. Try changing the PHP version and reinstalling it.

**Comment by ORyong** [comment]
I used PHP8.1 and MySQL 5.7 as recommended by Xera.

> > When I tried to install Xera, the last step of the installation step: redirection. Click the redirect button and you will jump to / admin / regeister. But the page is 404 and there is no directory in the host file directory.
> 
> 
> 
> > Register and redirect to mydomain/admin/regeister, but this page does not exist. ![Screenshot_20241031_102754_com microsoft emmx](https://private-user-images.githubusercontent.com/169452446/381801980-b7f26014-53c2-4a4c-8723-6d066da2a546.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDE4NTAsIm5iZiI6MTczMDQ0MTU1MCwicGF0aCI6Ii8xNjk0NTI0NDYvMzgxODAxOTgwLWI3ZjI2MDE0LTUzYzItNGE0Yy04NzIzLTZkMDY2ZGEyYTU0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNjEyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTBjYzUwOGE2ZmM5MzYyNjJkMGI1YTY3Zjg3MjA5YzFmMTlkZTAzM2VkZDYzMjVkMTcxNDEwZTViMGJiYWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yRcABuV_YeSra6vYlWDEUlOQ8o_Uw85HO6cqSWpvu0w) ![Screenshot_20241031_103113](https://private-user-images.githubusercontent.com/169452446/381802289-ca4eedb6-d73f-4414-8fcf-11fa3b4ed050.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDE4NTAsIm5iZiI6MTczMDQ0MTU1MCwicGF0aCI6Ii8xNjk0NTI0NDYvMzgxODAyMjg5LWNhNGVlZGI2LWQ3M2YtNDQxNC04ZmNmLTExZmEzYjRlZDA1MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNjEyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTg0ZGRmMmUyYzI3NmFkNWE5YWYzZWFkNmY5MzNkMDE1OTU3ODE3MjIxZjdjMDFiNjE4MDBiYzg4NDIzMDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x12gjcS9c0RfwpamcEtNsO49KaWnTP8wn0ZMeRtsZ-Y)
> 
> Please check your PHP configuration. Try changing the PHP version and reinstalling it.

**Comment by santydesignscr** [comment]
It's because you're on a subdirectory, you need to adapt the .htaccess file or install in a subdomain instead

**Comment by ORyong** [comment]
Instead of putting him in a subdomain, I put him in another brand new domain and in that domain directory, and attempted to install both in that domain's directory and in a subdirectory of that domain catalog. Both were 404.
> It's because you're on a subdirectory, you need to adapt the .htaccess file or install in a subdomain instead

**Comment by santydesignscr** [comment]
Ohh, I see, you're using nginx, Xera is intended to be used on apache server, or apache server through nginx proxy

**Comment by ORyong** [comment]
Yes.you are right. Thanks for your help 
> Ohh, I see, you're using nginx, Xera is intended to be used on apache server, or apache server through nginx proxy
