### ISSUE TITLE
clients and mofh accounts in 1 page only show 1 member

### ISSUE THREAD

**Issue by NotKRhero** [mahtab2003/Xera#177]
why is it?

**Comment by santydesignscr** [comment]
Can you share more details like screenshots?

**Comment by tanguy-fgl** [comment]
You need to change records per page in API settings under the admin control

**Comment by santydesignscr** [comment]
> You need to change records per page in API settings under the admin control

You're right, I forgot that the default value for that is 1 🤦‍♂️
