### ISSUE TITLE
User registered with the same username

### ISSUE THREAD

**Issue by ash3T** [mahtab2003/Xera#184]
<img width="1127" alt="Screenshot 2024-11-26 at 12 02 41 PM" src="https://github.com/user-attachments/assets/e0e9e01c-ec2a-46fc-8891-a1d06d81a243">

I believe this is a bug. Simply raise this for your guys' attention. Please let me know if you need more information. I don't how people can do this.

**Comment by itsmerosu** [comment]
> <img alt="Screenshot 2024-11-26 at 12 02 41 PM" width="1127" src="https://private-user-images.githubusercontent.com/72311810/390070596-e0e9e01c-ec2a-46fc-8891-a1d06d81a243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzQ3MzAsIm5iZiI6MTczMjY3NDQzMCwicGF0aCI6Ii83MjMxMTgxMC8zOTAwNzA1OTYtZTBlOWUwMWMtZWMyYS00NmZjLTg4OTEtYTFkMDZkODFhMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyMjcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZThmYTg4ODZhNmJiNzc4NTEyZTI5N2RjNTI5MDliZDg4OGM4NDg2NmQyZDJlMTgzYzhmNTJmYjgxYmQ3YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xxD5u3m3fScDhPhOck5HVgCYajnnpw5f4aT4oi7986I">
> I believe this is a bug. Simply raise this for your guys' attention. Please let me know if you need more information. I don't how people can do this.

I reviewed your screenshot and noticed that it is a MOFH account screenshot. It shows a label for hosting accounts. I want to clarify that the label can be anything users choose when creating a hosting account, and this is not a significant issue for a MOFH panel.

**Comment by ash3T** [comment]
Got it. Thanks for your reply. How about this following one: register two user accounts with same username and email address

<img width="1123" alt="Screenshot 2024-11-27 at 11 35 37 AM" src="https://github.com/user-attachments/assets/080cf711-4daa-4aa6-b46d-728adb6a764a">

**Comment by itsmerosu** [comment]
> Got it. Thanks for your reply. How about this following one: register two user accounts with same username and email address
> 
> <img alt="Screenshot 2024-11-27 at 11 35 37 AM" width="1123" src="https://private-user-images.githubusercontent.com/72311810/390499317-080cf711-4daa-4aa6-b46d-728adb6a764a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjY1NjksIm5iZiI6MTczMjcyNjI2OSwicGF0aCI6Ii83MjMxMTgxMC8zOTA0OTkzMTctMDgwY2Y3MTEtNGRhYS00YWE2LWI0NmQtNzI4YWRiNmE3NjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE2NTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZmUzYTMzMmNiZjM1YTk3OTcwZWRlNzFmZWExYTdiODE4MTQzODk4NDQ3YTMyNThlYjM0YTQzOTU1MTMwZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BdEPDWhryVpPRo8ysMuQsW079AwsjBdX_RtgCf5PEcI">

The Account Name functions similarly to a hosting account label; however, it is not possible to use the same email address for both. I noticed one account has ****7@gmail.com, while the other has ****6@gmail.com. I might be mistaken about the email issue, so please provide a clear screenshot to help identify the main problem.

**Comment by ash3T** [comment]
Yes. You are right about the two different email addresses. Thanks very much for your reply and your patience.
