### ISSUE TITLE
Avatar function

### ISSUE THREAD

**Issue by ash3T** [mahtab2003/Xera#186]
<img width="595" alt="Screenshot 2024-11-27 at 11 51 35 AM" src="https://github.com/user-attachments/assets/88b192fb-c2f4-4a33-9201-b00ce158a88a">

<img width="435" alt="Screenshot 2024-11-27 at 11 52 19 AM" src="https://github.com/user-attachments/assets/6c0e1326-75bc-4908-80c3-8a764519c1d8">

Some one changed his own avatar image, I don't think we got this function, am I right?

**Comment by itsmerosu** [comment]
> <img alt="Screenshot 2024-11-27 at 11 51 35 AM" width="595" src="https://private-user-images.githubusercontent.com/72311810/390501369-88b192fb-c2f4-4a33-9201-b00ce158a88a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjY5NjUsIm5iZiI6MTczMjcyNjY2NSwicGF0aCI6Ii83MjMxMTgxMC8zOTA1MDEzNjktODhiMTkyZmItYzJmNC00YTMzLTkyMDEtYjAwY2UxNThhODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE2NTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNTE3Yjk0MTBhZTY0Yjk5MmQzMmI3MDI2OTE4ZjRhN2I0YTg1Mzg1Y2NjMjAzYzZkZWFiZjZlOWQ5MzQ4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZvOWDbFuz9uYUUFeVQZ2AEQc8kI6UIikAZF0HPPp2yk"> <img alt="Screenshot 2024-11-27 at 11 52 19 AM" width="435" src="https://private-user-images.githubusercontent.com/72311810/390501399-6c0e1326-75bc-4908-80c3-8a764519c1d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjY5NjUsIm5iZiI6MTczMjcyNjY2NSwicGF0aCI6Ii83MjMxMTgxMC8zOTA1MDEzOTktNmMwZTEzMjYtNzViYy00OTA4LTgwYzMtOGE3NjQ1MTljMWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE2NTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMzgxYTlhYmYwMzM2NmIwNmQwODU0NmMzODVhYjI2ZDMwODk5NTcyZDViZDg5MWJmYmM5NzYxNmE3MDczNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kx3lmkjWLaSuMVCTg7i1C-34sSY_CcjGLaCsLoh8VOU">
> Some one changed his own avatar image, I don't think we got this function, am I right?

Users can log in using their GitHub account, or if their email is linked to a Gravatar, XERA will automatically retrieve data such as name and profile image from the relevant servers.

**Comment by ash3T** [comment]
Got it. Thanks for your reply.
