### ISSUE TITLE
Incorrect Account IP address shown

### ISSUE THREAD

**Issue by greenreader9** [mahtab2003/Xera#19]
![image](https://user-images.githubusercontent.com/75644395/182624594-1342defc-980e-4d58-820f-1067108c2a4f.jpeg)

This is the current code, set to only display this one IP when the account is active. While this IP is on the MOFH network, I don't think any free clients are assigned to it. 

Additionally, you cannot hard code in a value here, since each account is hosted on a different IP address. 

I recommend updating this value to get the correct IP address for the account, or remove it altogether, since it currently provides incorrect (and useless) information.

**Comment by mahtab2003** [comment]
ok i will replace it

**Comment by mahtab2003** [comment]
problem fixed
