### ISSUE TITLE
No database connection error

### ISSUE THREAD

**Issue by webersec** [mahtab2003/Xera#22]
After completing the installation process and on clicking redirect it shows - No database connection settings were found in the database config file

**Comment by MeVsGOD** [comment]
I had same problem replacing database.php file from older version fixed the problem.

**Comment by webxjoin** [comment]
I lost all of my data I have to restore asap...

🤣🤣🤣🤣

**Comment by mahtab2003** [comment]
you can only install xera once well i don't try installing xera again and again.
by the way every time xera is installed old xera installation will be removed automatically (I forget to tell this before. 😅).

**Comment by mahtab2003** [comment]
error fixed i just put the wrong file 😋.

**Comment by webxjoin** [comment]
I can now download the script.zip right and do a clean installation

**Comment by webersec** [comment]
thank you
