### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by webxjoin** [mahtab2003/Xera#23]
An error occurred, please try again later.

**Comment by mahtab2003** [comment]
your smtp settings are invalid

**Comment by webxjoin** [comment]
> your smtp settings are invalid

Is valid you have a problem with the code here some errors on the register Page that no one is pointing out ![Screenshot_20220815-062655_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184594652-bed545d9-156f-41e5-9e0c-322716f4cebb.jpg)

**Comment by webxjoin** [comment]
@mahtab2003 my hosting support said the setting are correct the program is from the SMTP service provider ![Screenshot_20220815-062620_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184595142-e620159e-0cec-4c7f-b561-1a27cc1fc38f.jpg)

**Comment by mahtab2003** [comment]
can you give me your hosting account username and password so i can help you out

**Comment by webxjoin** [comment]
I will highly appreciate if you just tech me what to do

**Comment by mahtab2003** [comment]
use test smtp settings
hostname: mail.nxtshost.eu.org
username: [test@nxtshost.eu.org](mailto:test@nxtshost.eu.org)
password: forxeratesting
port: 587

**Comment by eldzejgm** [comment]
@mahtab2003 I have the same problem and correct smtp settings

**Comment by mahtab2003** [comment]
> @mahtab2003 I have the same problem and correct smtp settings

what settings are you using

**Comment by eldzejgm** [comment]
checking the smtp module shows an error, but during registration the mail is sent so it probably works

**Comment by eldzejgm** [comment]
@mahtab2003 mam pytanie jak zacząć używać gogetssl ?

**Comment by eldzejgm** [comment]
@mahtab2003 I have a question, how to start using gogetssl ?

**Comment by mahtab2003** [comment]
> @mahtab2003 I have a question, how to start using gogetssl?

Create an account on gogetssl.com and apply for reseller program. then after an hour or two you will receive an email. after that login to your gogetssl account at my.gogetssl.com and go to Menu > Reseller Modules > Api Settings. and generate an api password. put api username and password password in xera api settings and thats all....

**Comment by eldzejgm** [comment]
And is it 100% free? @mahtab2003

**Comment by mahtab2003** [comment]
yes @eldzejgm

**Comment by webxjoin** [comment]
SMTP ain't working correctly for me

**Comment by mahtab2003** [comment]
> SMTP ain't working correctly for me

don't know bro maybe the firewall is interupting

**Comment by webxjoin** [comment]
> use test smtp settings hostname: mail.nxtshost.eu.org username: [test@nxtshost.eu.org](mailto:test@nxtshost.eu.org) password: forxeratesting port: 587

**i try this its still saying errors**

**Comment by webxjoin** [comment]
> use test smtp settings hostname: mail.nxtshost.eu.org username: [test@nxtshost.eu.org](mailto:test@nxtshost.eu.org) password: forxeratesting port: 587

![SharedScreenshot3](https://user-images.githubusercontent.com/111163768/188126371-651c304f-dd58-43ae-be45-8aad80586cea.jpg)
 

**Still not working i dont know what to do**

**Comment by webxjoin** [comment]
this has been solve through the help of my hosting provider Namecheap

Thank you for your patience.

We have enabled debug for your website and could locate the following error log:
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-09-02 15:04:22 --> Severity: Notice --> fwrite(): send of 5 bytes failed with errno=32 Broken pipe /home/userinfo/public_app/system/libraries/Email.php 2268

In the file mentioned in the log (/home/userinfo/public_app/system/libraries/Email.php) we could find the empty SMTP settings. We filled them with the ones that are placed in your admin dashboard. 

After that, the error log did not appear anymore but the error was not fixed as well.

Hence, we would rather suggest you consult with a web developer regarding this topic.

Please check it on your side and let us know if we can be of any further assistance.

Looking forward to hearing from you.

**Comment by mahtab2003** [comment]
this error is complicated
