### ISSUE TITLE
Account Stick to Pending instead of Active (Callback URL)

### ISSUE THREAD

**Issue by webxjoin** [mahtab2003/Xera#24]
This is the biggest problem since I replaced whmcs with Xera. I have to manually activate account through database.

**Comment by greenreader9** [comment]
This is going to be because you setup your callback incorrectly.

**Comment by mahtab2003** [comment]
> This is going to be because you setup your callback incorrectly.

you are right

**Comment by BastelPichi** [comment]
Please note that if you run Xera on Free Hosting, callbacks may not work.

**Comment by WavaAdrian** [comment]
If you are using ifastnet hosting you need to change callback URL from https://yourdomain.com/c/mofh to http://yourdomain.com/c/mofh in mofh control panel.

And then it will work.

**Comment by BastelPichi** [comment]
> If you are using ifastnet hosting you need to change callback URL from https://yourdomain.com/c/mofh to http://yourdomain.com/c/mofh in mofh control panel.
> 
> And then it will work.

Have you tested this? This should only work if you not have a SSL cert, which is reccomendet with Xera,

**Comment by mahtab2003** [comment]
> 

even if you have a valid ssl certificate some doesn't support https post request from other sites.

**Comment by BastelPichi** [comment]
Well with a redirect that shouldnt work but idk

**Comment by mahtab2003** [comment]
yup with redirection that won't work.

**Comment by webxjoin** [comment]
All the settings are correct but callback not working

**Comment by webxjoin** [comment]
callback is not working

**Comment by BastelPichi** [comment]
> callback is not working

Please share your xera url, a screenshot of the callback url configuration i xera and a screenshot from myownfreehost. Also where are you hosting xera on?

**Comment by webxjoin** [comment]
okay

**Comment by webxjoin** [comment]
XERA
![callback for xera](https://user-images.githubusercontent.com/111163768/188214119-7db616e8-819e-4f00-84f9-37d74b1f2d78.jpg)


MOFH Panel
![mofh](https://user-images.githubusercontent.com/111163768/188214145-b74a6d2c-2ca2-4920-a88d-c03d079782b9.jpg)

**Comment by BastelPichi** [comment]
Please share your Xera URL.

**Comment by webxjoin** [comment]
why

**Comment by BastelPichi** [comment]
For example to check wether you got proper SSL, or have an https redirect.

**Comment by mahtab2003** [comment]
> For example to check wether you got proper SSL, or have an https redirect.

you are right

**Comment by mahtab2003** [comment]
callback response does not work on https redirection.

**Comment by BastelPichi** [comment]
ill try some stuff. https works with MOFH callback usually

**Comment by webxjoin** [comment]
okay how can know if i have https redirect

**Comment by BastelPichi** [comment]
> okay how can know if i have https redirect

Go to http://yoursite.com and see if you get reidrected to https://youtsite.com

**Comment by roshan1885** [comment]
Same issue
Even its on http
![image](https://user-images.githubusercontent.com/81822450/188437437-9a8ad0e3-afe0-40b8-9b6f-cbe9fb7fb984.png)
![image](https://user-images.githubusercontent.com/81822450/188437733-d039485f-0593-408a-a8e4-40826abdb802.png)

**Comment by BastelPichi** [comment]
Well basically:
 - If you have an https redirect, you CANNOT use the http version.
 - If you have no SSL cert, you CANNOT use the https version.
 - We believe you have to use the http version.
 - You should exclude the callback from your rewriterules to fix this.

**Comment by roshan1885** [comment]
That is i should remove the force redirect to https?

**Comment by BastelPichi** [comment]
> That is i should remove the force redirect to https?

![grafik](https://user-images.githubusercontent.com/63782569/188495495-6389df38-d44a-4471-b49b-0d071b26e55d.png)

**Comment by roshan1885** [comment]
> > That is i should remove the force redirect to https?
> 
> ![grafik](https://user-images.githubusercontent.com/63782569/188495495-6389df38-d44a-4471-b49b-0d071b26e55d.png)

What callback? 
U mean that force redirect to https na?

My .htaccess
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .*$ index.php?/$1 [L]
</IfModule>


# Force redirect from http to https
RewriteEngine On
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://freewh.gq/$1 [R,L]
```

I understans what u are saying
But how shall I exclude it?
I don't know .htaccess
Like i have to make a rule which will exclude the callback url from force https?

**Comment by BastelPichi** [comment]
https://stackoverflow.com/questions/35598608/exclude-specific-url-from-https-redirect

**Comment by webxjoin** [comment]
> https://stackoverflow.com/questions/35598608/exclude-specific-url-from-https-redirect

i did not understand the article

**Comment by roshan1885** [comment]
Bru now i reinstalled Xera on a subdomain
I configured everything
I didnt put force redirect via cloudflare or .htaccess
And, i also checked going to http version of the api, and it works! You can try: http://client.freewh.gq/c/mofh
But the account is still on pending

Should i try with http://client.freewh.gq/index.php/c/mofh instead of http://client.freewh.gq/c/mofh ?

@mahtab2003 bro i need ur help

**Comment by mahtab2003** [comment]
> 

you should use http://client.freewh.gq/c/mofh

**Comment by mahtab2003** [comment]
> Bru now i reinstalled Xera on a subdomain I configured everything I didnt put force redirect via cloudflare or .htaccess And, i also checked going to http version of the api, and it works! You can try: http://client.freewh.gq/c/mofh But the account is still on pending
> 
> Should i try with http://client.freewh.gq/index.php/c/mofh instead of http://client.freewh.gq/c/mofh ?
> 
> @mahtab2003 bro i need ur help

@OnionDev1885  you should use http://client.freewh.gq/c/mofh

**Comment by roshan1885** [comment]
> > Bru now i reinstalled Xera on a subdomain I configured everything I didnt put force redirect via cloudflare or .htaccess And, i also checked going to http version of the api, and it works! You can try: http://client.freewh.gq/c/mofh But the account is still on pending
> > Should i try with http://client.freewh.gq/index.php/c/mofh instead of http://client.freewh.gq/c/mofh ?
> > @mahtab2003 bro i need ur help
> 
> @OnionDev1885 you should use http://client.freewh.gq/c/mofh

I am using that only
But still account stays on pending status
I tested the api and it works
The account is activated in mofh panel but not in Xera panel
Even tho force redirect to https is disabled on whole site + i gave the callback url in http

**Comment by webxjoin** [comment]
**There is a problem between the callback and the database**

**Comment by mahtab2003** [comment]
> **There is a problem between the callback and the database**

let me try a few tweaks

**Comment by roshan1885** [comment]
> **There is a problem between the callback and the database**

fixed

> > **There is a problem between the callback and the database**
> 
> let me try a few tweaks

fixed

Thank you everyone for your time

**Comment by mahtab2003** [comment]
welcome

**Comment by 4yx** [comment]
> @OnionDev1885 said:
> fixed

How was it fixed? Did you take any additional steps or was disabling the HTTPS redirect what was needed?

**Comment by roshan1885** [comment]
@4yx 

I did some changes:
> Disabled Force Redirect to https
> Added some lines of .htaccess to fix some errors
> Made the callback url to http on mofh panel

My .htaccess file:
![image](https://user-images.githubusercontent.com/81822450/190137748-b3c9e190-39af-4f2c-a2b8-53503987de98.png)
Code: (for direct copy paste)
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [NC,L] 
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule .*$ index.php?/$1 [L]
</IfModule>
```

**Comment by 4yx** [comment]
> @4yx
> 
> I did some changes:
> 
> > Disabled Force Redirect to https
> > Added some lines of .htaccess to fix some errors
> > Made the callback url to http on mofh panel
> 
> My .htaccess file: ![image](https://user-images.githubusercontent.com/81822450/190137748-b3c9e190-39af-4f2c-a2b8-53503987de98.png) Code: (for direct copy paste)
> 
> ```
> <IfModule mod_rewrite.c>
>     RewriteEngine On
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteRule ^(.*)$ index.php [NC,L] 
> </IfModule>
> 
> <IfModule mod_rewrite.c>
>     RewriteEngine On
>     RewriteBase /
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteRule .*$ index.php?/$1 [L]
> </IfModule>
> ```

Thank you for providing the contents and adding them in code format!

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
