### ISSUE TITLE
✔️Errors I found that need to be fixs

### ISSUE THREAD

**Issue by webxjoin** [mahtab2003/Xera#26]
✅REDIRECT 

![Screenshot_20220815-114733_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184630144-4cc8b66b-912c-424d-8da6-0eed4a23b90a.jpg)

✅USER ACCOUNT SETTINGS

![Screenshot_20220815-114838_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184630278-03e5e14c-4f43-461b-ada1-2d71a2a8d482.jpg)

✅ VIEW ACCOUNT DOMAINS SECTION

![Screenshot_20220815-114626_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184630464-648b4b74-895c-44ba-8c2a-fce0288025e9.jpg)

✅ SMTP 

![Screenshot_20220815-115745_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184631175-70210270-93ba-4552-8533-a2ab4d4cc4ea.jpg)

❌❌❌Follow Up ❌❌❌

👉 NAMECHEAP SUPPORT STAFF

![Screenshot_20220815-062620_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184631767-f49b7f73-da92-45c8-824e-d25b64677bcd.jpg)

👉 API MOFH 

👉 SMTP SENDGARD

![Screenshot_20220815-115600_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184631890-8f952319-3807-4353-969c-68ad58c1576c.jpg)

✅✅✅✅✅✅✅✅✅
PLEASE HELP ME ASAP 
✅✅✅✅✅✅✅✅✅

**Comment by webxjoin** [comment]
✅API MOFH

![Screenshot_20220815-120206_Chrome.jpg](https://user-images.githubusercontent.com/111163768/184632166-f32347f6-6006-4d75-918b-71327a1eca87.jpg)

**Comment by webersec** [comment]
in my case smtp is working fine but whenever user tries to create an account by typing in the subdomain details and click on redirect/configure it doesn't prompt the user to configuration page/tab.

**Comment by gilect-com** [comment]
Make sure "SMTP Status" is set to active.

**Comment by mahtab2003** [comment]
i will fix it up soon

**Comment by mahtab2003** [comment]
use test smtp settings
hostname: mail.nxtshost.eu.org
username: test@nxtshost.eu.org
password: forxeratesting
port: 587

**Comment by MeVsGOD** [comment]
I had only user account settings view
Same type page ( solution replace setting.php from older version,ex-1.2.2)
but others are working for me

**Comment by webxjoin** [comment]
> i will fix it up soon

Have you resolve the problems?

**Comment by mahtab2003** [comment]
yes i have resolved problems

**Comment by webersec** [comment]
i have also encountered the same problem "Accounts stucks to pending".......

**Comment by mahtab2003** [comment]
I don't what's happening some host support https and some host support http. change protocol and then create a new account wait 10 minutes if not works then change protocol and retry.

**Comment by webxjoin** [comment]
its difficult
