### ISSUE TITLE
i cant connect to MySQL on localhost

### ISSUE THREAD

**Issue by zeroninefourfour** [mahtab2003/Xera#30]
im testing it on my local computer,but on install.php,it success to install.when i go to register/login page. it give an error
```
A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: controllers/U.php

Line Number: 7
```

**Comment by zeroninefourfour** [comment]
it seems like its a bug...after i checked the code. mysql password and blablablabla didnt changed

**Comment by tanguy-fgl** [comment]
Maybe import manually db.sql in your local Php My Admin

**Comment by zeroninefourfour** [comment]
it seems like install.php has some problem....

**Comment by zeroninefourfour** [comment]
it only import db.sql to database,didnt change config file

**Comment by tanguy-fgl** [comment]
It works fine on my local server make sure you have xammp for php 7.4.29 installed

**Comment by tanguy-fgl** [comment]
It's my version that I use what's your php version ?

**Comment by zeroninefourfour** [comment]
7.4 (XAMPP)

**Comment by zeroninefourfour** [comment]
OR I FORGOT TO CHMOD IT 😆😆?

**Comment by tanguy-fgl** [comment]
No, make sure you have Apache and MySQL enabled
![image](https://user-images.githubusercontent.com/44116544/185343207-c08403f0-40ac-4ebf-a496-80fb41504299.png)
After create a database called xera on [PhpMyAdmin](http://localhost/phpmyadmin). After extract Xera in htdocs folder of your Xammp installation, and go to localhost/xera. Install  Xera and set MySQL information:
 - MySQL Server: localhost
 - Db name: xera
 - DB Password: leave empty

**Comment by zeroninefourfour** [comment]
yep,after i changed config file and database config file it worked. so i think theres some problem with install.php

**Comment by mahtab2003** [comment]
if you are using mac or linux the install.php need file edit permission to install xera.

**Comment by zeroninefourfour** [comment]
do u mean chmod?

**Comment by mahtab2003** [comment]
> do u mean chmod?

yes

**Comment by zeroninefourfour** [comment]
ok
