### ISSUE TITLE
User Login / Register Page Header Logo Disappear 

### ISSUE THREAD

**Issue by webxjoin** [mahtab2003/Xera#41]
there's no image showing up on those two pages accept for the admin page
![SharedScreenshot1](https://user-images.githubusercontent.com/111163768/187686959-7cc17158-6d80-40d1-b198-d8683db1c9a0.jpg)

**Comment by ghost** [comment]
Check Xera/assets/default/img/*.*

**Comment by webxjoin** [comment]
i uploaded all the images not its not showing up on the two pages

**Comment by mahtab2003** [comment]
let me check

**Comment by webxjoin** [comment]
okay

**Comment by webxjoin** [comment]
are you done

**Comment by mahtab2003** [comment]
fixed
