### ISSUE TITLE
Ablility To Create More Then One Admin

### ISSUE THREAD

**Issue by AwesomePerson2** [mahtab2003/Xera#42]
Is it possible to make more than one admin?

**Comment by 4yx** [comment]
I do not think there is currently, but +1 for me as a feature suggestion. Multiple admins would be nice, and perhaps the ability to make some roles and edit their permissions, like for example a support team role that has access only on specific areas (like ticket replying).

**Comment by AwesomePerson2** [comment]
im currently looking at editing the A.php to allowed more then one admin

**Comment by AwesomePerson2** [comment]
if you have discord i could reach out and let you know if it works

**Comment by 4yx** [comment]
> if you have discord i could reach out and let you know if it works

Alright, I have an invisible username right now so it might be hard to add me, but I'll post it in code format just in case you're able to get it to work:
```᲼᲼#9121```

I'll be going off now though, so I'll probably see your message tomorrow. You can also share your Discord with me if you're unable to add me via my email: ```anyxp@protonmail.com```.

**Comment by AwesomePerson2** [comment]
![Capture](https://user-images.githubusercontent.com/112724753/188751827-8181525f-3761-495c-8091-1e7c2b626cd1.PNG)
is this you by any chance

**Comment by 4yx** [comment]
Yes. I assume you are who I think you are?

**Comment by AwesomePerson2** [comment]
yes

**Comment by 4yx** [comment]
Oh, lol. Nice seeing you here!

**Comment by AwesomePerson2** [comment]
So after looking around the best method i saw that can do this would be editing the mysql database hopefully @mahtab2003  can add a multi-admin system in the future

**Comment by AwesomePerson2** [comment]
wouldnt work

**Comment by mahtab2003** [comment]
hm let me think

**Comment by AwesomePerson2** [comment]
Please add more admin feature

**Comment by AgentDeath253** [comment]
I am the same person as awesomeperson2

**Comment by mahtab2003** [comment]
> I am the same person as awesomeperson2

Firstly i don't think xera can support multi vendors system and secondly the mail structure is complicated as well

**Comment by AgentDeath253** [comment]
please @mahtab2003

**Comment by greenreader9** [comment]
You should just be able to use SQL statements and add another row the the database. I don't really see how it can cause an issue (And if it does, it takes two clicks to remove it). 

Editing after re-reading: what exactly is causing the issue? The mailing system? The login system?

**Comment by AgentDeath253** [comment]
i dont do mysql

**Comment by AgentDeath253** [comment]
also im trying to add more admins

**Comment by mahtab2003** [comment]
> You should just be able to use SQL statements and add another row the the database. I don't really see how it can cause an issue (And if it does, it takes two clicks to remove it).
> 
> Editing after re-reading: what exactly is causing the issue? The mailing system? The login system?

mailing system

**Comment by AgentDeath253** [comment]
> You should just be able to use SQL statements and add another row the the database. I don't really see how it can cause an issue (And if it does, it takes two clicks to remove it).
> 
> Editing after re-reading: what exactly is causing the issue? The mailing system? The login system?
again its more of a feature request muti admin support, I have been trying to make it where I could have more then one admin

**Comment by mahtab2003** [comment]
> > You should just be able to use SQL statements and add another row the the database. I don't really see how it can cause an issue (And if it does, it takes two clicks to remove it).
> > Editing after re-reading: what exactly is causing the issue? The mailing system? The login system?
> > again its more of a feature request muti admin support, I have been trying to make it where I could have more then one admin

it is not that simple

**Comment by AgentDeath253** [comment]
Solved Please Close

**Comment by AgentDeath253** [comment]
> You should just be able to use SQL statements and add another row the the database. I don't really see how it can cause an issue (And if it does, it takes two clicks to remove it).
> 
> Editing after re-reading: what exactly is causing the issue? The mailing system? The login system?

yeah its really is that simple

**Comment by mahtab2003** [comment]
there is nothing i can do in this case
