### ISSUE TITLE
[SCHEDULED FOR DELETION]

### ISSUE THREAD

**Issue by 4yx** [mahtab2003/Xera#44]
If you could remove this issue, it would be greatly appreciated. I'm not sure why GitHub bugged out on me.

**Comment by mahtab2003** [comment]
what do you mean

**Comment by 4yx** [comment]
> what do you mean

I accidentally created two issues instead of one. 
Maintainers of the repository should see this option under the participants section:
![](https://img001.prntscr.com/file/img001/bzGgkCYeQbK6zqPegB3CGg.png)
I'd appreciate it if you could delete this issue, however if you don't want to create confusion, I'll simply close it and we can leave it as is.

**Comment by mahtab2003** [comment]
ok
