### ISSUE TITLE
The "fourm" misspelling

### ISSUE THREAD

**Issue by 4yx** [mahtab2003/Xera#45]
I wanted to post this initially on https://fourm.xera.eu.org, however it appears the forum is broken, as it won't allow me to post, and some extensions are also displaying weirdly. Either that, or my account needs verification from an admin, in which case sorry I wasn't patient.

I was browsing through the files and saw that "forum" was misspelled as "fourm". At first I considered it a normal misspelling, however I see that this forum's name is also "fourm", and the variable name (the one controlling forum-related settings), is also "fourm". With that in mind, I corrected the misspelling in the visual aspect (where something appeared as "Fourm" in settings, it now appears as "Forum"), however I did not do so for the variables.

I'm afraid that if I updated the variables, most Xera installations might break, as the database entry will most likely remain as "fourm", and host owners will need to manually update it to "forum". With that in mind, should the variable be kept as is? I'm unsure if it's a misspelling, a feature, or something that started as a misspelling and became a feature. I could easily make a PR updating it (thanks, VSCode/ium!), but as I said, it might break most installations.

Thanks!

**Comment by mahtab2003** [comment]
no need to do this because visual name can be easily change in language files.

**Comment by 4yx** [comment]
Alright, I agree. Thanks!
