### ISSUE TITLE
Letsencrypt ssl features

### ISSUE THREAD

**Issue by MeVsGOD** [mahtab2003/Xera#47]
Please add letsencrypt ssl features to xera.

**Comment by mahtab2003** [comment]
ok ok

**Comment by OnionDev1885** [comment]
> ok ok

hey bro,
i found a broken page on xera admin client
![image](https://user-images.githubusercontent.com/81822450/190137202-bba88bc7-1dc3-4002-942e-a51abc6097ec.png)

**Comment by MeVsGOD** [comment]
> ok ok

Thanks 😊

**Comment by zeroninefourfour** [comment]
i think it will not supported on Free Hosting?Maybe?

**Comment by mahtab2003** [comment]
yes

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
