### ISSUE TITLE
Does Xera Support Office SMTP

### ISSUE THREAD

**Issue by AgentDeath253** [mahtab2003/Xera#57]
Same As The Title

**Comment by mahtab2003** [comment]
Maybe no

**Comment by roshan1885** [comment]
I guess no
Bcuz i tried with my Microsoft 365 SMTP and it didn't worked :(

**Comment by AgentDeath253** [comment]
could it be added?

**Comment by roshan1885** [comment]
Idk that. I never tried. 
The Microsoft smtp didn't worked for me so i choosed mailjet which is good.

**Comment by roshan1885** [comment]
@AgentDeath253 if your issue is solved, can u close it?
Once more: The office/Microsoft 365 SMTP doesn't works for me in Xera. I better use Mailjet which is good and gives about 2k emails/month

**Comment by AgentDeath253** [comment]
i use mailgun

**Comment by lynxdevv** [comment]
nah, office smtp needs tls secured connection which is not available in xera.
