### ISSUE TITLE
Can a new release be published?

### ISSUE THREAD

**Issue by 4yx** [mahtab2003/Xera#59]
[First mentioned](https://github.com/mahtab2003/Xera/issues/49#issuecomment-1259738301) in #49, I believe all the changes between https://github.com/mahtab2003/Xera/compare/1.2.8...dev are enough to warrant a new release, as they contain some critical fixes and improve Xera overall.

Would it be easy/possible to have a new release?

**Comment by mahtab2003** [comment]
i will make new release

**Comment by 4yx** [comment]
Nice, thanks!
