### ISSUE TITLE
u forgot to add gogetssl table 💀(datebase file)

### ISSUE THREAD

**Issue by zeroninefourfour** [mahtab2003/Xera#6]
i got this error,when i enable db_debug mode i know you forget add gogetssl table
<img width="1666" alt="截圖 2022-06-21 下午2 35 31" src="https://user-images.githubusercontent.com/69704016/174732370-914b4371-7b65-4a43-b5e4-72554d97faee.png">
.

**Comment by ImLoadingUuU** [comment]
<img width="405" alt="截圖 2022-06-21 下午2 39 36" src="https://user-images.githubusercontent.com/69704016/174733050-9d8aba91-6964-4853-9cd6-0624d670f9b6.png">
and there it say it will insert is_ssl table,but that picture says is_gogetssl table🤔
gogetssl or ssl?

**Comment by mahtab2003** [comment]
Sorry. I did forget😅. Now it is fixed.
