### ISSUE TITLE
500 Error while installing xera.

### ISSUE THREAD

**Issue by EasyTechniques** [mahtab2003/Xera#60]
I get a 500 error on my website while installing xera. Plz give me a solution for this.

**Comment by 4yx** [comment]
> I get a 500 error on my website while installing xera. Plz give me a solution for this.

At which step of the installation are you getting a 500 error?
What PHP version are you using?

**Comment by EasyTechniques** [comment]
i am using PHP 8.0 and I got error after extracting xera-dev.zip on my domains root directory

**Comment by WavaAdrian** [comment]
https://fourm.xera.eu.org/d/18-how-to-fix-500-internal-server-error

This is a Fix.

**Comment by EasyTechniques** [comment]
If I install xera on XAMPP, it works fine. But when I install xera on cPanel, it gives me 500 error

**Comment by 4yx** [comment]
> i am using PHP 8.0 and I got error after extracting xera-dev.zip on my domains root directory

If I'm not mistaken, PHP 8.0 is not supported by Xera, you need to run it on PHP 7.4.

**Comment by EasyTechniques** [comment]
Thanks for your support! Now it started working!!!

**Comment by 4yx** [comment]
> Thanks for your support! Now it started working!!!

You're welcome, glad it helped!

On a different note, the README should probably be changed. ``PHP v7.2 or above.``  can make people assume PHP 8 is supported, which it doesn't seem to be.
