### ISSUE TITLE
CSR Code

### ISSUE THREAD

**Issue by chippytech** [mahtab2003/Xera#63]
Why it is asking for a CSR Code instead of a domain name for SSL?

**Comment by chippytech** [comment]
Don't want to advertise a free SSL tool forever.

**Comment by 4yx** [comment]
> Why it is asking for a CSR Code instead of a domain name for SSL?

It uses that CSR code to generate the certificate for the domain. It's the way the tool was implemented. Why that way was chosen, I have no clue.



> Don't want to advertise a free SSL tool forever.

You can always modify the implementation, or create your own tool.
