### ISSUE TITLE
Takes Too long to load

### ISSUE THREAD

**Issue by EasyTechniques** [mahtab2003/Xera#64]
When i click register button on register page after filling the form, it takes some time and it redirects me to "Request Timeout" page.
I also changed PHP Version to 7.4 and I also increased values in php.ini files on cPanel. But it remains same. Can anyone tell me how to fix this?
![Screenshot (8)](https://user-images.githubusercontent.com/101200234/197107072-f80de51e-4ba9-48a7-a09b-74a9eb49bd70.png)
![Screenshot (10)](https://user-images.githubusercontent.com/101200234/197107097-3fcb22b0-a6c3-464f-a0eb-f864279451fb.png)

**Comment by 4yx** [comment]
The request seems to be going through though, as my account was created. Strange.

**Comment by mahtab2003** [comment]
if smtp is turned off then it will work fine

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
