### ISSUE TITLE
can't setup properly

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/Xera#65]
after installation it told me to register the admin user but get error

![image](https://user-images.githubusercontent.com/93871548/197680286-798adb46-60d4-4bcb-9737-d019f757467d.png)

**Comment by mahtab2003** [comment]
.htaccess file error

**Comment by PiyushYadav007** [comment]
What should I do?

**Comment by PiyushYadav007** [comment]
Please reply i need to set this up

**Comment by roshan1885** [comment]
Your .htaccess should look like this:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [NC,L] 
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule .*$ index.php?/$1 [L]
</IfModule>
```

**Comment by PiyushYadav007** [comment]
Done but it is showing same error

**Comment by roshan1885** [comment]
> Done but it is showing same error 

Can u post a picture of your current .htaccess?

**Comment by PiyushYadav007** [comment]
Ok now It worked thanks
