### ISSUE TITLE
Getting problem with eu.org

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/Xera#68]
I changed my nameservers on eu.org but i am unable to configure them on cloudflare or on any other services what should I do?

**Comment by roshan1885** [comment]
Seez if you think that you will use yourdomain.eu.org as providing a subdomain in your hosting company, then don't use cloudflare.
If u want to use cloudflare, then you can't use yourdomain.eu.org for providing Subdomains.

**Comment by PiyushYadav007** [comment]
I know but the problem is i already pointed nameservers to cloudflare but the cloudflare and ns checker shows to point nameservers to cloudflare 

What should I do?

**Comment by roshan1885** [comment]
there may be some issues with the domain side, or cloudflare side. Can u say me how is it related to Xera?

**Comment by SpookyKipper** [comment]
eu.org has nothing related to Xera
