### ISSUE TITLE
I want customize xera.

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/Xera#69]
Is there any guide or suggestions for customizing xera and what are the main folders to customise it and the folder to add new features.

**Comment by roshan1885** [comment]
As per as i customize, the functions folder that is major, is app/controllers
And for css is assets folder, and contents is template folder.
There are lot more folders where the texts can be customised like app/languages/english
For rest functions, u can just search then and get their directory

**Comment by PiyushYadav007** [comment]
Ok and thankyou.

What if we add multiple mofh api integration like whenever a user creates max account from 1 mofh api the api changes to next one for that user only then will he able to create more than 3 accounts

**Comment by roshan1885** [comment]
see, the account limit is not set my mofh api. It is set by this Xera code. 
According to mofh, users can create unlimited hosting accounts (I guess that so)
You can change the limit from: `app/controllers/U.php` in line 904. Make sure you also change the limit content from: `template/default/page/user/accounts.php` in lines: 16-18, and 72

**Comment by PiyushYadav007** [comment]
According to mofh  a user can create upto 3 accounts using api.

**Comment by roshan1885** [comment]
umm, is that so?
idk then...

Let me test it. Just give me about 5 minutes

**Comment by PiyushYadav007** [comment]
And how to add yandex SMTP and Google SMTP option

**Comment by OnionDev1885** [comment]
No, thats not correct. I created 4th account
![image](https://user-images.githubusercontent.com/81822450/198261670-178572ad-93f7-435b-8e6a-16309bfc28e1.png)

**Comment by PiyushYadav007** [comment]
> No, thats not correct. I created 4th account ![image](https://user-images.githubusercontent.com/81822450/198261670-178572ad-93f7-435b-8e6a-16309bfc28e1.png)

But your one account is deactivated
Try to create 4 active accounts

**Comment by PiyushYadav007** [comment]
And how to customise client are?

**Comment by PiyushYadav007** [comment]
And how to customise client are?

**Comment by OnionDev1885** [comment]
> > No, thats not correct. I created 4th account ![image](https://user-images.githubusercontent.com/81822450/198261670-178572ad-93f7-435b-8e6a-16309bfc28e1.png)
> 
> But your one account is deactivated Try to create 4 active accounts

![image](https://user-images.githubusercontent.com/81822450/198262667-6d308540-a4b0-42bc-b69c-2045efaf62d5.png)

**Comment by roshan1885** [comment]
> And how to customise client are?

edit in `template/default/page/<admin/user>/<page>.php`

**Comment by PiyushYadav007** [comment]
> > > No, thats not correct. I created 4th account ![image](https://user-images.githubusercontent.com/81822450/198261670-178572ad-93f7-435b-8e6a-16309bfc28e1.png)
> > 
> > 
> > But your one account is deactivated Try to create 4 active accounts
> 
> ![image](https://user-images.githubusercontent.com/81822450/198262667-6d308540-a4b0-42bc-b69c-2045efaf62d5.png)

Then this is awesome

**Comment by PiyushYadav007** [comment]
> > And how to customise client are?
> 
> edit in `template/default/page/<admin/user>/<page>.php`

No i mean the details of the website to show on client area like website name and logo

**Comment by OnionDev1885** [comment]
> > > > No, thats not correct. I created 4th account ![image](https://user-images.githubusercontent.com/81822450/198261670-178572ad-93f7-435b-8e6a-16309bfc28e1.png)
> > > 
> > > 
> > > But your one account is deactivated Try to create 4 active accounts
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/81822450/198262667-6d308540-a4b0-42bc-b69c-2045efaf62d5.png)
> 
> Then this is awesome

Edit these files and lines:
`app/controllers/U.php`: line 904
`template/default/page/user/accounts.php`: Line 10

**Comment by PiyushYadav007** [comment]
And from where did you get homepage for your website?

**Comment by OnionDev1885** [comment]
> 

do u mean navbar?
> > If yes, then edit `template/default/page/includes/user/navbar.php`
> > If no, then can you please send the screenshot of the area that you want to edit?

**Comment by PiyushYadav007** [comment]
And the gogetssl will automatically changed once the SSL certificate is expired for us resellers.

**Comment by roshan1885** [comment]
> And the gogetssl will automatically changed once the SSL certificate is expired for us resellers.

idk, none of my certs expired till now

---

> And from where did you get homepage for your website?

for clients, the homepage is same as accounts page. I never thought to make those pages, so idk about those routes. I simply use client.domain.tld as Xera, and domain.tld as info page

**Comment by PiyushYadav007** [comment]
" domain.tld as info page" i am talking about this one
And customising these details are easy in mofhy

**Comment by roshan1885** [comment]
> " domain.tld as info page" i am talking about this one

I took an open source code, and modified it. Then uploaded to the site.

---
> And customising these details are easy in mofhy

But MOFHY is not secure as Xera. If you wanna use MOFHY, then you can use that too

**Comment by PiyushYadav007** [comment]
I was asking about gogetssl certificate because i read it somewhere i don't know but i did and one more thing there is a php code of let's encrypt to automatically add and replace ssl certificate in php we can intigrat it xera so us and our clients do not have to keep worrying about ssl

**Comment by PiyushYadav007** [comment]
> > " domain.tld as info page" i am talking about this one
> 
> I took an open source code, and modified it. Then uploaded to the site.
> 
> > And customising these details are easy in mofhy
> 
> But MOFHY is not secure as Xera. If you wanna use MOFHY, then you can use that too

Nah i am not going to use it now

**Comment by roshan1885** [comment]
> I was asking about gogetssl certificate because i read it somewhere i don't know but i did and one more thing there is a php code of let's encrypt to automatically add and replace ssl certificate in php we can intigrat it xera so us and our clients do not have to keep worrying about ssl

idk anything about Let's encrypt, and ig it requires Commands to generate ssl. 
**If anyone else here knows about Let's Encrypt, then please assist him.**

**Comment by PiyushYadav007** [comment]
Check this 
https://letsencrypt.org/docs/client-options/

And this
https://freessl.tech/

**Comment by PiyushYadav007** [comment]
What about SMTP can we integrate Gmail and yandex SMTP?

**Comment by PiyushYadav007** [comment]
What did you use for SMTP and professional domain

**Comment by roshan1885** [comment]
> What about SMTP can we integrate Gmail and yandex SMTP?

I dont think about gmail, since it didnt worked for me. And i didn't tried Yandex. I use mailjet, which is good and it works on Xera.

**Comment by PiyushYadav007** [comment]
> > What about SMTP can we integrate Gmail and yandex SMTP?
> 
> I dont think about gmail, since it didnt worked for me. And i didn't tried Yandex. I use mailjet, which is good and it works on Xera.

Ok but what should I do about eu.org domain i changed its nameservers but it didn't worked so what should I do

**Comment by PiyushYadav007** [comment]
> > What about SMTP can we integrate Gmail and yandex SMTP?
> 
> I dont think about gmail, since it didnt worked for me. And i didn't tried Yandex. I use mailjet, which is good and it works on Xera.

I was saying to add these in xera like mofh so both of these can work

**Comment by roshan1885** [comment]
> > > What about SMTP can we integrate Gmail and yandex SMTP?
> > 
> > 
> > I dont think about gmail, since it didnt worked for me. And i didn't tried Yandex. I use mailjet, which is good and it works on Xera.
> 
> I was saying to add these in xera like mofh so both of these can work

See, M a beginner in php. Idk a much.
If you know, then you can add and open a pull request

**Comment by PiyushYadav007** [comment]
Ok and how to check that the core is secure or not?
but what should I do about eu.org domain i changed its nameservers but it didn't worked so what should I do

**Comment by PiyushYadav007** [comment]
What about adding a sorting feature according to the status of the client's website activate, deactivated, suspend or deleted.

**Comment by greenreader9** [comment]
@OnionDev1885 @PiyushYadav007 

While you can create unlimited accounts using the API, iFastNet imposes a limit of 3 accounts per email address. It does not look like they actively use bots to detect this, but they will permanently suspended all your accounts (Sometimes without backup) if they find you are violating the terms (which state 3 accounts).

**Comment by roshan1885** [comment]
> What about adding a sorting feature according to the status of the client's website activate, deactivated, suspend or deleted.

As mentioned earlier, i have just started with php, and i m not at advanced level.
If you want, you can code it on their specific pages and open a pull request

**Comment by roshan1885** [comment]
> @OnionDev1885 @PiyushYadav007
> 
> While you can create unlimited accounts using the API, iFastNet imposes a limit of 3 accounts per email address. It does not look like they actively use bots to detect this, but they will permanently suspended all your accounts (Sometimes without backup) if they find you are violating the terms (which state 3 accounts).

Hmm
Thanks for the info.

**Comment by greenreader9** [comment]
>What about adding a sorting feature according to the status of the client's website activate, deactivated, suspend or deleted.

I could do that fairly easily, but I don't have time at the moment. (You could pay me for a pull ASAP 🤑 )

You can do it with the SQL query that is fetching the accounts.

**Comment by PiyushYadav007** [comment]
No thanks i will do that and create a pull

**Comment by SpookyKipper** [comment]
> " domain.tld as info page" I am talking about this one

It's your own homepage, Xera is just a client area, it only does the job of being a Client Area. You have to make your own



> Ok and how to check that the core is secure or not?

There are currently no known security vulnerabilities, but why don't you check yourself by looking into all the files :)



> Check this https://letsencrypt.org/docs/client-options/
> And this https://freessl.tech/

Xera has GoGetSSL implemented for SSL Certificates. If you want Let's Encrypt Certs, you can develop it yourself.
I haven't tried, but I don't think it will be too hard.

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
