### ISSUE TITLE
404 on register

### ISSUE THREAD

**Issue by bopv2** [mahtab2003/Xera#7]
So I just finished setting up for the second time Xera due this error in the register link
The website is https://control.cpvp.ga/index.php/u/login
The main is https://cpvp.ga/

Whenever I go to control.cpvp,ga in login to press the register hyperlink, it redirects me to /u/register witch doesnt exist!

Also I couldnt signup in the forum because of this error saying "validation.recaptcha"
![image](https://user-images.githubusercontent.com/97548973/176655914-55060e62-4740-4021-b405-6d8cc00fcc05.png)

**Comment by mahtab2003** [comment]
Dear user you have not setup your xera installation correctly.
The base url should be https://control.cpvp.ga/panel/index.php/u/login because you have your xera installation in the panel directory.

For the forum let me check.

**Comment by bopv2** [comment]
Ok I will try to change the config to that!

**Comment by bopv2** [comment]
Also I do have it in a directory cause when i go to control.cpvp.ga it shows me 403 error!

**Comment by bopv2** [comment]
> Dear user you have not setup your xera installation correctly. The base url should be https://control.cpvp.ga/panel/index.php/u/login because you have your xera installation in the panel directory.
> 
> For the forum let me check.

So i changed it to that and it cant find the css as it looks like

**Comment by mahtab2003** [comment]
> Also I do have it in a directory cause when i go to control.cpvp.ga it shows me 403 error!

You should add an index file that redirect users from https://control.cpvp.ga/index.php/u/login to https://control.cpvp.ga/panel/index.php/u/login

**Comment by bopv2** [comment]
Ok

**Comment by bopv2** [comment]
So i have fixed the register issue THO the css doesnt seem to be found?

**Comment by mahtab2003** [comment]
What url have you added to your config file?

**Comment by bopv2** [comment]
https://control.cpvp.ga/panel/index.php

**Comment by mahtab2003** [comment]
Base url should be https://control.cpvp.ga/panel/

**Comment by bopv2** [comment]
Hey im sorry for being inactive the messages werent showing
Anyways can you give me a couple mins cause the cpanel account of cpvp got terminated

**Comment by bopv2** [comment]
Alright its reactivating, sorry for taking your time

**Comment by mahtab2003** [comment]
> Alright its reactivating, sorry for taking your time

That's fine.

**Comment by bopv2** [comment]
So well i set it to that and register doesnt work again!

**Comment by bopv2** [comment]
It goes to panel/u/register not in index.php/u/register

**Comment by bopv2** [comment]
Also i put it back in control.cpvp.ga and removed it from folder (and yes i changed the base url)

**Comment by bopv2** [comment]
DirectoryIndex index.php index.html index.htm index2.html
on an htaccess might fix it i think

**Comment by bopv2** [comment]
NVM it didnt

**Comment by mahtab2003** [comment]
The .htaccess file is not working.

**Comment by mahtab2003** [comment]
Just fix htaccess file and it will work fine.

**Comment by bopv2** [comment]
Ok

**Comment by bopv2** [comment]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@foo.tld to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by bopv2** [comment]
https://fourm.xera.eu.org/d/18-how-to-fix-500-internal-server-error ima try this

**Comment by bopv2** [comment]
YES IT WORKED!!!!

**Comment by bopv2** [comment]
THANKS SOO MUCH!

**Comment by mahtab2003** [comment]
You are always welcome
