### ISSUE TITLE
The accounts created by api are not active 

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/Xera#71]
The accounts created by mofh api are not active but the domain at mofh panel it is active how to solve this issue. And when i changed the status from pending to active using database cpanel url is not opening giving error

**Comment by mahtab2003** [comment]
callback URL not working

**Comment by PiyushYadav007** [comment]
What should I do to fix it

**Comment by SpookyKipper** [comment]
try both http and https in the MOFH panel

Also, note that Xera is discontinued, MOFH-R is a new Client Area

**Comment by PiyushYadav007** [comment]
Why xera is discontinued?

> try both http and https in the MOFH panel
> 
> Also, note that Xera is discontinued, MOFH-R is a new Client Area

**Comment by mahtab2003** [comment]
> Why xera is discontinued?
> 
> > try both http and https in the MOFH panel
> > Also, note that Xera is discontinued, MOFH-R is a new Client Area

I'm tired of it. it is a mess code is complex and sometimes i am stuck  can't understand what i have created sometimes.

**Comment by PiyushYadav007** [comment]
> > Why xera is discontinued?
> > > try both http and https in the MOFH panel
> > > Also, note that Xera is discontinued, MOFH-R is a new Client Area
> 
> I'm tired of it. it is a mess code is complex and sometimes i am stuck can't understand what i have created sometimes.

Ok but why the accounts are being created by it shows pending?

Do i have to change their status manually?

**Comment by mahtab2003** [comment]
> > > Why xera is discontinued?
> > > > try both http and https in the MOFH panel
> > > > Also, note that Xera is discontinued, MOFH-R is a new Client Area
> > 
> > 
> > I'm tired of it. it is a mess code is complex and sometimes i am stuck can't understand what i have created sometimes.
> 
> Ok but why the accounts are being created by it shows pending?
> 
> Do i have to change their status manually?

yes you have to

**Comment by SpookyKipper** [comment]
> Do i have to change their status manually?

No you don't, but you need to set the callback url in the MOFH panel

**Comment by PiyushYadav007** [comment]
> > Do i have to change their status manually?
> 
> No you don't, but you need to set the callback url in the MOFH panel

So exactly what I have to set in mofh panel

**Comment by mahtab2003** [comment]
> 

the callback url

**Comment by PiyushYadav007** [comment]
Like this in panel.myownfreehost.com
http://myhosting24.ml/c/mofh

**Comment by mahtab2003** [comment]
use https instead of http after setting that create an account and wait for 10 minutes if status doesn't changes automatically use http again and redo the same process

**Comment by PiyushYadav007** [comment]
Are these problems fixed in mofh- r?

**Comment by mahtab2003** [comment]
> Are these problems fixed in mofh- r?

for xera and mofh-r both

**Comment by PiyushYadav007** [comment]
I have to put http://myhosting24.ml/c/mofh this in panel.myownfreehost.com will it work

**Comment by mahtab2003** [comment]
> I have to put http://myhosting24.ml/c/mofh this in panel.myownfreehost.com will it work

try http://myhosting24.ml/c/mofh if not work then try https://myhosting24.ml/c/mofh

**Comment by Wava123** [comment]
Change ![image](https://user-images.githubusercontent.com/117023322/202167524-4521680c-6cc5-4549-aab9-48a32fc5ca81.png)
To
![image](https://user-images.githubusercontent.com/117023322/202167437-5f8f6b81-b30c-496e-b29c-b7ad413690cd.png)

Change https to http. Then it will work.
