### ISSUE TITLE
Internal Server Error After completing the install.php install

### ISSUE THREAD

**Issue by KaidenTheCEO** [mahtab2003/Xera#74]
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@foo.tld to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by mahtab2003** [comment]
check app/config/config.php

**Comment by KaidenTheCEO** [comment]
> check app/config/config.php

Hey, what exactly am I checking for?

**Comment by mahtab2003** [comment]
by the way i don't know either. just change application environment from production to development in [MOFH-R_ROOT]/index.php

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
