### ISSUE TITLE
Issue with admin/account.php

### ISSUE THREAD

**Issue by coozywana** [mahtab2003/Xera#78]
It has the same problem where it shows 0 accounts. Eg I have 10 web hosting accounts, and it shows 0/10 accounts showing. The same thing happened with Clients.php but I fixed that.

**Comment by chippytech** [comment]
Please use <a href="http://github.com/GenerateApps/GenerateArea"> GenerateArea </a> instead.

**Comment by coozywana** [comment]
GenerateArea is the same as Xera

**Comment by leeteral** [comment]
> GenerateArea is the same as Xera

It's definitely not. It's a fork of Xera with more features, bug fixes, etc. and Xera isn't maintained anymore, which means that there will be security flaws in the future, but that's not the case with GenerateArea since it's actively maintained.

**Comment by coozywana** [comment]
> > GenerateArea is the same as Xera
> 
> It's definitely not. It's a fork of Xera with more features, bug fixes, etc. and Xera isn't maintained anymore, which means that there will be security flaws in the future, but that's not the case with GenerateArea since it's actively maintained.

GenerateArea is broken, it does not have more features than Xera and has way more bugs than Xera. Most of the pages don't even have css. Xera is way more stable than GenerateArea.

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
