### ISSUE TITLE
No accounts are showing in Admin Panel in my client area

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/Xera#79]
I am currently using xera but in the my client page it is not showing clients and when i click on manage it gives 500 error.
![image](https://user-images.githubusercontent.com/93871548/220960592-7fbdcd16-d8b0-4269-82a2-e960a1ef98ea.png)

![image](https://user-images.githubusercontent.com/93871548/220960208-0556b6f9-8d90-46f2-9623-0a59f9bc7f50.png)

**Comment by SpookyKipper** [comment]
Xera is discontinued, but please provide some kind of logs

**Comment by mahtab2003** [comment]
logs?

**Comment by PiyushYadav007** [comment]
I know that xera is discontinued but it will be better if this problem gets solved. Anyone can tell me why I am getting this problem.

**Comment by SpookyKipper** [comment]
You may try an installation of GenerateArea, as it should be actively maintained, and it's a fork of Xera.

But please give us logs, copy the files and database to your own computer can give it to us.

**Comment by PiyushYadav007** [comment]
> You may try an installation of GenerateArea, as it should be actively maintained, and it's a fork of Xera.
> 
> But please give us logs, copy the files and database to your own computer can give it to us.

Ok I can provide the logs but where I have to Find Them?

**Comment by SpookyKipper** [comment]
copy the files and database and run xera on your own computer.
you should have a console

**Comment by mahtab2003** [comment]
There was no replies so this issue is considered to be resolved
