### ISSUE TITLE
The action you have requested is not allowed.

### ISSUE THREAD

**Issue by bopv2** [mahtab2003/Xera#8]
Hey im very sorry for annoying you again, but when I try to register or login I get a "The action you have requested is not allowed." even without anything in the boxes, do you mind helping me?

**Comment by mahtab2003** [comment]
First let me check.

**Comment by mahtab2003** [comment]
Go to your xera's app/config/config.php in line 451. Change TRUE to FALSE and try again. Maybe it will work fine.

**Comment by bopv2** [comment]
Unable to load the requested file: helpers/custom_helper.php

**Comment by bopv2** [comment]
I get that error

**Comment by bopv2** [comment]
Alright so i fixed that error but now when i press register or login it just refreshes the page and doesnt log in neither register

**Comment by mahtab2003** [comment]
Let me check

**Comment by bopv2** [comment]
Okay!

**Comment by mahtab2003** [comment]
Can you share your FTP information so i can check.

**Comment by bopv2** [comment]
Ok but where? Whats your discord

**Comment by bopv2** [comment]
I lost the link

**Comment by mahtab2003** [comment]
I don't use discord. Send am an email at mahtabhassan159@gmail.com

**Comment by bopv2** [comment]
Alright

**Comment by bopv2** [comment]
Sent!

**Comment by mahtab2003** [comment]
Received

**Comment by bopv2** [comment]
Alright

**Comment by mahtab2003** [comment]
Working fine. Don't change cookie settings.

**Comment by bopv2** [comment]
Ok lemme try!

**Comment by bopv2** [comment]
So im getting an error saying "The Name field cannot contain illegal characters" when the name is just `axonz`

**Comment by mahtab2003** [comment]
There must be a first_name and a last name in name field

**Comment by bopv2** [comment]
ok

**Comment by bopv2** [comment]
thanks soo much for the support! and again sorry for keeping you busy

**Comment by mahtab2003** [comment]
Thats ok
