### ISSUE TITLE
CNAME Records Disabled From ROOT

### ISSUE THREAD

**Issue by itsmerosu** [mahtab2003/Xera#85]
Hi there,

CNAME Records are disabled due to a bug that exists in the name servers causing the CNAMEs to no longer work. So please do something for the SSL verification method to File Upload or Admin Email Features. 

Thank you and stay safe !

 Thank You
![support](https://github.com/mahtab2003/Xera/assets/56078030/e3dd631d-019a-4860-9182-9c58226cbbff)

**Comment by 4yx** [comment]
CNAME Records can still be added from ``cpanel.{your_domain}/panel/indexpl.php?option=cnamerecords``, and they seem to be functional at the moment (but probably not fully, which is why the option is still hidden).

**Comment by itsmerosu** [comment]
Thanks
