### ISSUE TITLE
XERA LITE NOT SYNCING

### ISSUE THREAD

**Issue by davisvawiz** [mahtab2003/Xera#86]
hello? 

My xera is not syncing thus not automatically activating new accounts.

This is my callback link [http://www.davisvawiz.buzz/Client/c/mofh](https://www.davisvawiz.buzz/Client/c/mofh)

Also this link is not working [https://www.davisvawiz.buzz/Client/a/view_ssl/](https://www.davisvawiz.buzz/Client/a/view_ssl/)

Thanks!

**Comment by PiyushYadav007** [comment]
same here it is working if it is set on http but when i switch back to https it doesn't work.
If the api url is set to http then callback doesn't work and if the https site doesn't work.

I wonder how did I set it up the last time

**Comment by mahtab2003** [comment]
This issue is closed due to inactivity.
