### ISSUE TITLE
Login Button Not Working !!

### ISSUE THREAD

**Issue by itsmerosu** [mahtab2003/Xera#88]
Login as a client is not working from the admin dashboard. Please check once and fix this issue on the next update and please provide a quick update. it has been a year, and there are no updates from the developer.

**Comment by PiyushYadav007** [comment]
It is working you just have to go to your base url or change the redirect url to your base url in app/controllers/a.php view_client function

**Comment by PiyushYadav007** [comment]
Which version you are using this is currently broken

**Comment by itsmerosu** [comment]
@PiyushYadav007 Current Version?

**Comment by PiyushYadav007** [comment]
> @PiyushYadav007 Current Version?

It is working you just have to go to main domain or the domain on which you have setup the xera after clicking login as client.
