### ISSUE TITLE
Ticket Mailing Problem !

### ISSUE THREAD

**Issue by itsmerosu** [mahtab2003/Xera#89]
I am using the latest XERA and everything working fine but I figured out one problem on my system. When I respond to any ticket, the ticket reply post mail goes to 1st account email on the database (is_user), but not to the account email that created the ticket. 

In summary,
Ticket Created Account Email: 100@gmail.com
Ticket Responed Email Send to: 1@gmail.com (This email is my 1st used email as a client in my xera dashboard)

Any solution for this @mahtab2003 @4yx @FuryCraft

Thank You

**Comment by mahtab2003** [comment]
Will be reviewed shortly.

**Comment by santydesignscr** [comment]
Will be fixed soon

**Comment by santydesignscr** [comment]
Hello I reviewed the mentioned error, but I don't get such error

**Comment by santydesignscr** [comment]
A ticket from the first account dn DB:
User replied ticket:
![image](https://github.com/mahtab2003/Xera/assets/88201812/03c44533-d4ac-48c7-928e-20497e18b702)
Email:
![Imagen de WhatsApp 2024-07-08 a las 20 57 42_53826e40](https://github.com/mahtab2003/Xera/assets/88201812/326beb35-d7a6-4f69-889c-13a59a6746f6)

Admin reply that ticket:
![image](https://github.com/mahtab2003/Xera/assets/88201812/9625e649-9e50-4031-8de8-bccde6b23bfc)
Email:
![Imagen de WhatsApp 2024-07-08 a las 20 57 17_57dc1605](https://github.com/mahtab2003/Xera/assets/88201812/27fe6f9e-a494-46bd-b544-b169ad8bf0a7)


With another account:
Reply from user:
![image](https://github.com/mahtab2003/Xera/assets/88201812/e8f82693-9ff3-4cf6-9a24-b98aec9205ca)
Email:
![Imagen de WhatsApp 2024-07-08 a las 21 02 01_23d0e309](https://github.com/mahtab2003/Xera/assets/88201812/bace5d65-e7d7-4362-b26f-4ead4983e80e)

Reply from admin:
![image](https://github.com/mahtab2003/Xera/assets/88201812/af2f53bd-e33e-46e8-997b-8ff4695e99af)
Email:
![Imagen de WhatsApp 2024-07-08 a las 21 04 15_4a82c2b6](https://github.com/mahtab2003/Xera/assets/88201812/2b6346d1-f2b8-4145-8457-7dd3f0a8f858)

**Comment by itsmerosu** [comment]
Not in my dashboard and now I have already left XERA."

**Comment by itsmerosu** [comment]
I'm experiencing issues on my end and have already reported the problem.
#133

**Comment by santydesignscr** [comment]
Hello, sorry but right now Xera is on a complete code migration to Codeigniter 4, not posible to fix right now

**Comment by santydesignscr** [comment]
When the migration is completed all errors will be fixed

**Comment by itsmerosu** [comment]
I'm closing this issue and opening a new one because it contains the latest data and a screenshot for better understanding. You can proceed with your migration process, but please provide some steps to counter that issue, and I will take care of it.
