### ISSUE TITLE
issue with user

### ISSUE THREAD

**Issue by jpconstruction** [mahtab2003/Xera#90]
Dear Sir,
                  we install the xera but we facing a problem when user create mofh account the status account shows pending.

please tell me how to fix the issues.

Regards
Deepak Kumar
![Screenshot 2023-12-20 172116](https://github.com/mahtab2003/Xera/assets/83714092/b7f279e0-fba1-41c8-b0c1-0efe96bc1a3e)
![Screenshot 2023-12-20 172038](https://github.com/mahtab2003/Xera/assets/83714092/53d036e6-5d5c-45be-86f6-b8b46bc4ad77)

**Comment by itsmerosu** [comment]
Hey @jpconstruction 

Please check your call-back URL on the MOFH dashboard, If you made some mistake while placing the call-back URL then this problem shows.

Thank You
