### ISSUE TITLE
stmp not working

### ISSUE THREAD

**Issue by noisria** [mahtab2003/Xera#91]
stmp not working error : An error occured. Try again later.
i use `hosting webamil "cpanel"

port : 465
i use ssl

**Comment by itsmerosu** [comment]
Hey @noisria , 

I wanted to ensure you get the most secure email service from XERA. To ensure the highest level of protection for your sensitive data, please use the 587 port when sending and receiving emails. 

Thank you for taking the necessary steps to keep your information safe!

**Comment by noisria** [comment]
i use 587 but not working

**Comment by noisria** [comment]
i check my stmp with https://www.gmass.co/smtp-test
is working but in this script not working

**Comment by noisria** [comment]
![Screenshot_4](https://github.com/mahtab2003/Xera/assets/154697534/664d6412-13ed-49ae-b5d4-dd371eaf6474)

**Comment by noisria** [comment]
i test with all port : [25] [2525] [465] [587] but the same problem

**Comment by santydesignscr** [comment]
It is fixed now you can try the development version, you need to setup encryption option for the email
