### ISSUE TITLE
whois lookup not working

### ISSUE THREAD

**Issue by noisria** [mahtab2003/Xera#92]
page not working ERROR 500

**Comment by noisria** [comment]
check app\controllers\U.php

	function whois_lookup()
	{
		if($this->user->is_logged())
		{
			$data['title'] = 'whois_lookup';
			$this->load->helper('whois');

**Comment by greenreader9** [comment]
Share error logs

**Comment by betasio** [comment]
idk this whois lookup does not work how can we fix it

we get internal error 500
> Share error logs

**Comment by santydesignscr** [comment]
It will be fixed soon

**Comment by santydesignscr** [comment]
It's due to a limitation of MOFH, you can't use that feature in a free hosting, I will add an option to disable that features that will not work on MOFH (admin will be able to enable or disable it)

**Comment by betasio** [comment]
hello, its fine I have managed to fix it way before and its working for me very well it was a php 8.2 error u just need to do this change:

The change is relatively small, in line 227 of file "app\helpers\whois_helper.php" you'll need to replace the curly brace syntax with a bracket syntax, so change this:

			`if(($whoIsRecord != '') && ($whoIsRecord{0} != '#') && ($whoIsRecord{0} != '%')) {`
to this:

			`if(($whoIsRecord != '') && ($whoIsRecord[0] != '#') && ($whoIsRecord[0] != '%')) {`

**Comment by santydesignscr** [comment]
Ohhh, I don't know why Mehtab used that braked, let me update the code

b10fc8e4e8c1aa5bc182f2c985aa8c553c146c84 fixed the problem

**Comment by santydesignscr** [comment]
My production implementation of Xera set PHP 7.4 and I don't remember and my development server is set PHP 8.2, I only tested in production, effectively the error was on my development server and I don't seen

**Comment by mahtab2003** [comment]
> Ohhh, I don't know why Mehtab used that braked, let me update the code
> 
> [b10fc8e](https://github.com/mahtab2003/Xera/commit/b10fc8e4e8c1aa5bc182f2c985aa8c553c146c84) fixed the problem

Well the fact is i never read or write the code for that function i just copied it from Stackoverflow
