### ISSUE TITLE
problem email account_created

### ISSUE THREAD

**Issue by noisria** [mahtab2003/Xera#93]
email account_created not sending
email new_user sending working
i use protocol mail
public $protocol	= 'mail';		// mail/sendmail/smtp
because stmp not working with me

**Comment by noisria** [comment]
i use protocol stmp but same problem

**Comment by greenreader9** [comment]
Share error logs

**Comment by santydesignscr** [comment]
Please share more details so we can debug the error

**Comment by santydesignscr** [comment]
And test the last development version,  we added a encryption setting that can solve that issue with the SMTP, so please be sure that your SMTP server is working properly.

SMTP Encryption:
Port: 25 Encryption: None
Port: 465 Encryption: SSL
Port: 587 Encryption: TLS

**Comment by RaannaKasturi** [comment]
The isn't solved yet. when entered SMTP details and clicked on Test connection, it just keeps on loading until the server crashes. And, then after 10-15 minutes server starts. But, still can't send mails

**Comment by santydesignscr** [comment]
Did you set up correctly the encryption?

**Comment by RaannaKasturi** [comment]
Yes. I was using google SMTP

**Comment by santydesignscr** [comment]
Google SMTP is only available for business accounts, please try with another provider like brevo

**Comment by santydesignscr** [comment]
Additionally please confirm that you are using the development version, because the release doesn't contain this fix (we are working on another errors and some features to release a new version soon)

**Comment by RaannaKasturi** [comment]
Yes. I'm on development version. I tried Brevo SMTP at first. But, it didn't worked. So, I switched to Google SMTP.
Also, if possible can you join me for anydesk or Google Meet and help me debug the issue? I'm not much good at PHP. 
Here's my telegram: [https://t.me/RaannaKasturi](https://t.me/RaannaKasturi)

**Comment by santydesignscr** [comment]
So as we talked, it's fixed, I will close the issue
