### ISSUE TITLE
how do i fix

### ISSUE THREAD

**Issue by ghost** [mahtab2003/Xera#98]
![Skärmbild 2024-04-04 163007](https://github.com/mahtab2003/Xera/assets/163117122/40cfb2ea-e2f9-4ced-a1bd-52814e000149)

**Comment by greenreader9** [comment]
Make sure you have all the files uploaded, and in the correct location. That error means the file does not exist.

**Comment by mahtab2003** [comment]
This issue is closed due to inactivity.
