### ISSUE TITLE
Here's how you fix SMTP Error in Xera and MOFH-R

### ISSUE THREAD

**Issue by saurav-z** [mahtab2003/Xera#99]
Took me one whole day to fix this, I wrote article in my website check this and make sure to subscribe my youtube channel to support me.
Youtube:
https://youtube.com/@trachitz

Article:
https://ekg.com.np/email-issues-in-xera-and-mofh-r/

**Comment by greenreader9** [comment]
Vote to mark as closed: Advertisement, not an issue
